"""
LanceDB Integration Test Module
===============================
m_flow.tests.test_lancedb

Comprehensive tests for LanceDB vector database integration:
- Embedded vector storage and retrieval
- Table management and data lifecycle
- Integration with m_flow memory pipeline
- Multi-mode search operations
"""

import pathlib
import hashlib
import os

import m_flow
from m_flow.shared.logging_utils import get_logger
from m_flow.shared.files.storage import get_storage_config
from m_flow.data.models import Data
from m_flow.auth.methods import get_seed_user
from m_flow.search.types import RecallMode
from m_flow.search.operations import get_history

_logger = get_logger()


async def check_file_deletion_behavior(text_data: str, referenced_path: str):
    """
    Verifies correct file deletion behavior for m_flow data entries.

    Two distinct behaviors are tested:
    1. Files generated by m_flow: Should be removed when data entity is deleted
    2. Files referenced externally: Should persist after data entity deletion

    Args:
        text_data: Text content that was ingested by m_flow
        referenced_path: Path to externally referenced file
    """
    from sqlalchemy import select
    from m_flow.adapters.relational import get_db_adapter

    engine = get_db_adapter()

    # Test 1: m_flow-created files should be cleaned up
    async with engine.get_async_session() as session:
        content_digest = hashlib.md5(text_data.encode("utf-8")).hexdigest()

        data_entry = (await session.scalars(select(Data).where(Data.content_hash == content_digest))).one()

        local_path = data_entry.processed_path.replace("file://", "")
        assert os.path.isfile(local_path), f"File missing before deletion: {data_entry.processed_path}"

        await engine.delete_data_entity(data_entry.id)

        assert not os.path.exists(local_path), f"m_flow file should be removed: {data_entry.processed_path}"

    # Test 2: External references should not be deleted
    async with engine.get_async_session() as session:
        data_entry = (await session.scalars(select(Data).where(Data.processed_path == referenced_path))).one()

        local_path = data_entry.processed_path.replace("file://", "")
        assert os.path.isfile(local_path), f"File missing before deletion: {data_entry.processed_path}"

        await engine.delete_data_entity(data_entry.id)

        assert os.path.exists(local_path), f"External file should persist: {data_entry.processed_path}"


async def check_document_access(dataset_name: str):
    """
    Tests document ID retrieval for search operations.

    Validates both dataset-filtered and unfiltered document access.
    """
    from m_flow.auth.permissions.methods import get_document_ids_for_user

    user = await get_seed_user()

    # Dataset-specific retrieval
    dataset_docs = await get_document_ids_for_user(user.id, [dataset_name])
    assert len(dataset_docs) == 1, f"Dataset should contain 1 document, found {len(dataset_docs)}"

    # Full access retrieval
    all_accessible_docs = await get_document_ids_for_user(user.id)
    assert len(all_accessible_docs) == 2, f"User should access 2 documents, found {len(all_accessible_docs)}"


async def check_unbounded_search():
    """
    Tests that vector search with limit=None returns all matches.

    Guards against hidden default limits being applied in the search chain.
    """
    test_files_dir = pathlib.Path(__file__).parent / "test_data"
    quantum_path = test_files_dir / "Quantum_computers.txt"
    nlp_path = test_files_dir / "Natural_language_processing.txt"

    await m_flow.prune.prune_data()
    await m_flow.prune.prune_system(metadata=True)

    await m_flow.add(str(quantum_path))
    await m_flow.add(str(nlp_path))
    await m_flow.memorize()

    from m_flow.adapters.vector import get_vector_provider

    vector_db = get_vector_provider()

    query = "Tell me about Quantum computers"
    embedding = (await vector_db.embedding_engine.embed_text([query]))[0]

    search_results = await vector_db.search(
        collection_name="Entity_name",
        query_vector=embedding,
        limit=None,
    )

    # Common default limits are 5, 10, 15 - we should exceed all of these
    assert len(search_results) > 15, f"Unbounded search should return >15 results, got {len(search_results)}"


async def main():
    """
    Primary test runner for LanceDB integration validation.

    Sets up LanceDB configuration and executes full test suite.
    """
    # Configure embedded LanceDB
    m_flow.config.set_vector_db_config(
        {
            "vector_db_provider": "lancedb",
        }
    )

    # Initialize test storage paths
    test_root = pathlib.Path(__file__).parent
    data_dir = (test_root / ".data_storage" / "test_lancedb").resolve()
    system_dir = (test_root / ".mflow/system" / "test_lancedb").resolve()

    m_flow.config.data_root_directory(str(data_dir))
    m_flow.config.system_root_directory(str(system_dir))

    # Fresh start
    await m_flow.prune.prune_data()
    await m_flow.prune.prune_system(metadata=True)

    # Define test datasets
    nlp_ds = "natural_language"
    quantum_ds = "quantum"

    nlp_source = test_root / "test_data" / "Natural_language_processing.txt"
    quantum_source = test_root / "test_data" / "Quantum_computers.txt"

    await m_flow.add([str(nlp_source)], nlp_ds)
    await m_flow.add([str(quantum_source)], quantum_ds)
    await m_flow.memorize([quantum_ds, nlp_ds])

    # Validate document access
    await check_document_access(nlp_ds)

    # Search tests
    from m_flow.adapters.vector import get_vector_provider

    vector_db = get_vector_provider()

    concept_match = (await vector_db.search("Entity_name", "Quantum computer"))[0]
    concept_text = concept_match.payload["text"]

    # TRIPLET_COMPLETION mode
    completion_results = await m_flow.search(
        query_type=RecallMode.TRIPLET_COMPLETION,
        query_text=concept_text,
    )
    assert len(completion_results) > 0, "Graph completion returned empty results"
    _logger.info("Completion results count: %d", len(completion_results))

    # EPISODIC mode with dataset filter
    episodic_results = await m_flow.search(
        query_type=RecallMode.EPISODIC,
        query_text=concept_text,
        datasets=[quantum_ds],
    )
    assert len(episodic_results) > 0, "Episodic search returned empty results"
    _logger.info("Episodic results count: %d", len(episodic_results))

    # Filtered completion
    filtered_results = await m_flow.search(
        query_type=RecallMode.TRIPLET_COMPLETION,
        query_text=concept_text,
        datasets=[quantum_ds],
    )
    assert len(filtered_results) > 0, "Filtered completion returned empty results"

    # Search history verification
    active_user = await get_seed_user()
    history_entries = await get_history(active_user.id)
    assert len(history_entries) > 0, "History should not be empty"

    # Cleanup validation
    await m_flow.prune.prune_data()
    storage_cfg = get_storage_config()
    assert not os.path.isdir(storage_cfg["data_root_directory"]), "Data directory should be removed after prune"

    await m_flow.prune.prune_system(metadata=True)
    db_connection = await vector_db.get_connection()
    remaining_tables = await db_connection.table_names()
    assert len(remaining_tables) == 0, f"LanceDB should be empty after cleanup, found {len(remaining_tables)} tables"

    # Unbounded search test
    await check_unbounded_search()

    _logger.info("LanceDB integration tests completed successfully")


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
