"""
本地 Hub 部署管理器

支持在本地启动和管理 EigenFlux Hub 实例。
需要系统安装 Docker（推荐）或 Go 编译环境。
"""

import os
import json
import time
import shutil
import signal
import logging
import subprocess
from pathlib import Path
from typing import Optional, Dict, Any, List
from dataclasses import dataclass

from .config import EigenFluxConfig

logger = logging.getLogger(__name__)


@dataclass
class HubStatus:
    """Hub 运行状态"""
    running: bool
    pid: Optional[int] = None
    port: Optional[int] = None
    url: Optional[str] = None
    mode: str = "unknown"   # docker / native / process
    started_at: Optional[int] = None
    logs_tail: List[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return {
            "running": self.running,
            "pid": self.pid,
            "port": self.port,
            "url": self.url,
            "mode": self.mode,
            "started_at": self.started_at,
            "logs_tail": self.logs_tail or [],
        }


class EigenFluxHubManager:
    """EigenFlux Hub 管理器

    支持三种部署模式：
    1. Docker 模式（推荐，最简单）
    2. 源码编译模式（需要 Go 工具链）
    3. CLI 模式（使用 eigenflux 自带的 hub 命令）
    """

    def __init__(self, config: Optional[EigenFluxConfig] = None):
        from .config import get_config
        self.config = config or get_config()
        self._process: Optional[subprocess.Popen] = None
        self._docker_container_name: Optional[str] = None

    # ========== 环境检查 ==========

    def has_docker(self) -> bool:
        """检查 Docker 是否可用"""
        return shutil.which("docker") is not None

    def has_go(self) -> bool:
        """检查 Go 编译环境"""
        return shutil.which("go") is not None

    def get_available_mode(self) -> str:
        """获取可用的部署模式"""
        if self.has_docker():
            return "docker"
        if self.has_go():
            return "native"
        return "process"

    # ========== 配置生成 ==========

    def _ensure_data_dir(self) -> Path:
        """确保数据目录存在"""
        data_dir = Path(self.config.local_hub_data_dir)
        data_dir.mkdir(parents=True, exist_ok=True)
        (data_dir / "logs").mkdir(exist_ok=True)
        (data_dir / "storage").mkdir(exist_ok=True)
        (data_dir / "configs").mkdir(exist_ok=True)
        return data_dir

    def _generate_env_file(self) -> Path:
        """生成 Hub 所需的 .env 文件"""
        data_dir = self._ensure_data_dir()
        env_path = data_dir / "configs" / ".env.hub"
        content = f"""
# EigenFlux Hub Local Configuration
# Generated by MTSCOS AI System at {time.strftime('%Y-%m-%d %H:%M:%S')}

# 服务端口
HUB_PORT={self.config.local_hub_port}
HUB_HOST=0.0.0.0

# 数据存储
DATA_DIR=/app/data
STORAGE_DIR=/app/data/storage
LOG_DIR=/app/data/logs

# 管理员
ADMIN_TOKEN=mtscos-local-hub-admin-{os.getpid()}

# 匹配引擎
MATCH_THRESHOLD={self.config.match_threshold}
ENABLE_LOCAL_MATCHING={'true' if self.config.enable_local_matching else 'false'}

# 特性开关
ENABLE_BROADCAST=true
ENABLE_SUBSCRIPTION=true
ENABLE_INBOX=true
ENABLE_WEBSOCKET=true

# 限流
RATE_LIMIT_BROADCAST_PER_MIN=60
RATE_LIMIT_MATCH_PER_MIN=300
""".strip()
        env_path.write_text(content, encoding="utf-8")
        return env_path

    def _generate_config_yaml(self) -> Path:
        """生成 YAML 配置（可选）"""
        data_dir = self._ensure_data_dir()
        cfg_path = data_dir / "configs" / "hub.yaml"
        content = f"""
server:
  port: {self.config.local_hub_port}
  host: 0.0.0.0

storage:
  type: sqlite
  path: {data_dir / 'storage' / 'hub.db'}

matching:
  default_threshold: {self.config.match_threshold}
  enable_local: {self.config.enable_local_matching}

features:
  broadcast: true
  subscription: true
  inbox: true
  websocket: true

rate_limit:
  broadcast_per_minute: 60
  match_per_minute: 300
""".strip()
        cfg_path.write_text(content, encoding="utf-8")
        return cfg_path

    # ========== Docker 模式 ==========

    def _docker_compose_content(self) -> str:
        data_dir = self.config.local_hub_data_dir
        return f"""
version: "3.8"

services:
  eigenflux-hub:
    image: eigenflux/hub:latest
    container_name: eigenflux-local-hub
    ports:
      - "{self.config.local_hub_port}:{self.config.local_hub_port}"
    volumes:
      - "{data_dir}/storage:/app/data/storage"
      - "{data_dir}/logs:/app/data/logs"
      - "{data_dir}/configs:/app/data/configs"
    env_file:
      - "{data_dir}/configs/.env.hub"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:{self.config.local_hub_port}/api/v1/health"]
      interval: 30s
      timeout: 5s
      retries: 3
""".strip()

    def start_docker(self) -> HubStatus:
        """使用 Docker 启动 Hub"""
        if not self.has_docker():
            raise RuntimeError("Docker not available. Install Docker first.")

        data_dir = self._ensure_data_dir()
        self._generate_env_file()
        self._generate_config_yaml()

        compose_path = data_dir / "docker-compose.yml"
        compose_path.write_text(self._docker_compose_content(), encoding="utf-8")

        logger.info(f"[EigenFlux] Starting local Hub via Docker on port {self.config.local_hub_port}")

        # 拉镜像 + 启动
        try:
            subprocess.run(
                ["docker", "compose", "-f", str(compose_path), "pull"],
                check=False, timeout=300,
                capture_output=True, text=True,
            )
        except Exception as e:
            logger.warning(f"[EigenFlux] docker pull skipped: {e}")

        result = subprocess.run(
            ["docker", "compose", "-f", str(compose_path), "up", "-d"],
            capture_output=True, text=True, timeout=120,
        )
        if result.returncode != 0:
            raise RuntimeError(f"Failed to start Hub via docker: {result.stderr}")

        self._docker_container_name = "eigenflux-local-hub"
        return HubStatus(
            running=True,
            port=self.config.local_hub_port,
            url=f"http://localhost:{self.config.local_hub_port}",
            mode="docker",
            started_at=int(time.time()),
        )

    def stop_docker(self) -> bool:
        """停止 Docker Hub"""
        data_dir = self._ensure_data_dir()
        compose_path = data_dir / "docker-compose.yml"
        if not compose_path.exists():
            return False

        result = subprocess.run(
            ["docker", "compose", "-f", str(compose_path), "down"],
            capture_output=True, text=True, timeout=60,
        )
        return result.returncode == 0

    # ========== 源码编译模式 ==========

    def _clone_repo(self, target_dir: Path) -> bool:
        """克隆 EigenFlux 仓库"""
        if target_dir.exists():
            return True
        result = subprocess.run(
            ["git", "clone", "--depth", "1",
             "https://github.com/phronesis-io/eigenflux.git",
             str(target_dir)],
            capture_output=True, text=True, timeout=300,
        )
        return result.returncode == 0

    def build_from_source(self) -> Optional[Path]:
        """从源码编译 Hub 二进制"""
        if not self.has_go():
            logger.warning("[EigenFlux] Go not installed, cannot build from source")
            return None

        data_dir = self._ensure_data_dir()
        repo_dir = data_dir / "repo"
        if not self._clone_repo(repo_dir):
            logger.error("[EigenFlux] Failed to clone EigenFlux repo")
            return None

        logger.info("[EigenFlux] Building Hub from source...")
        result = subprocess.run(
            ["go", "build", "-o", "../hub-bin", "./api"],
            capture_output=True, text=True, timeout=600,
            cwd=str(repo_dir),
        )
        if result.returncode != 0:
            logger.error(f"[EigenFlux] Build failed: {result.stderr}")
            return None

        binary = data_dir / "hub-bin"
        logger.info(f"[EigenFlux] Hub built successfully: {binary}")
        return binary

    def start_native(self) -> HubStatus:
        """从源码编译并启动 Hub"""
        binary = self.build_from_source()
        if not binary or not binary.exists():
            raise RuntimeError("Failed to build Hub binary from source")

        self._generate_env_file()
        data_dir = self._ensure_data_dir()
        env_file = data_dir / "configs" / ".env.hub"

        # 读取环境变量
        env = os.environ.copy()
        with open(env_file) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, v = line.split("=", 1)
                    env[k] = v

        log_path = data_dir / "logs" / "hub.log"
        log_fh = open(log_path, "a", encoding="utf-8")

        self._process = subprocess.Popen(
            [str(binary)],
            cwd=str(data_dir),
            env=env,
            stdout=log_fh,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )

        logger.info(f"[EigenFlux] Native Hub started (PID={self._process.pid}) on port {self.config.local_hub_port}")
        return HubStatus(
            running=True,
            pid=self._process.pid,
            port=self.config.local_hub_port,
            url=f"http://localhost:{self.config.local_hub_port}",
            mode="native",
            started_at=int(time.time()),
        )

    # ========== 统一启动/停止 ==========

    def start(self, mode: Optional[str] = None) -> HubStatus:
        """启动本地 Hub（自动选择模式）"""
        mode = mode or self.get_available_mode()

        if mode == "docker":
            return self.start_docker()
        elif mode == "native":
            return self.start_native()
        else:
            return self.start_cli_mode()

    def start_cli_mode(self) -> HubStatus:
        """通过 CLI 模式启动（如果 CLI 已安装）"""
        from .client import EigenFluxClient
        client = EigenFluxClient(self.config)
        if not client.cli_installed():
            # 尝试安装 CLI
            client.cli_install()

        data_dir = self._ensure_data_dir()
        log_path = data_dir / "logs" / "hub.log"
        log_fh = open(log_path, "a", encoding="utf-8")

        env = os.environ.copy()
        env["EIGENFLUX_HOME"] = self.config.home_dir
        env["HUB_PORT"] = str(self.config.local_hub_port)

        self._process = subprocess.Popen(
            [client.cli_path_resolved(), "hub", "start",
             "--port", str(self.config.local_hub_port),
             "--data-dir", str(data_dir / "storage")],
            env=env,
            stdout=log_fh,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
        return HubStatus(
            running=True,
            pid=self._process.pid,
            port=self.config.local_hub_port,
            url=f"http://localhost:{self.config.local_hub_port}",
            mode="process",
            started_at=int(time.time()),
        )

    def stop(self) -> bool:
        """停止 Hub"""
        stopped = False
        # 停止 docker
        try:
            if self.stop_docker():
                stopped = True
        except Exception:
            pass
        # 停止进程
        if self._process and self._process.poll() is None:
            try:
                self._process.terminate()
                try:
                    self._process.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    self._process.kill()
                stopped = True
            except Exception:
                pass
            self._process = None
        return stopped

    def status(self) -> HubStatus:
        """获取当前 Hub 状态"""
        data_dir = self._ensure_data_dir()
        logs_tail: List[str] = []
        log_path = data_dir / "logs" / "hub.log"
        if log_path.exists():
            try:
                with open(log_path, "r", encoding="utf-8", errors="ignore") as f:
                    lines = f.readlines()
                    logs_tail = [l.rstrip() for l in lines[-20:]]
            except Exception:
                pass

        running = False
        pid = None

        if self._process and self._process.poll() is None:
            running = True
            pid = self._process.pid
        else:
            # 检查 docker
            if self.has_docker():
                result = subprocess.run(
                    ["docker", "ps", "--filter",
                     "name=eigenflux-local-hub", "--format", "{{.ID}} {{.Names}}"],
                    capture_output=True, text=True, timeout=5,
                )
                if result.returncode == 0 and "eigenflux-local-hub" in result.stdout:
                    running = True

        mode = "docker" if self._docker_container_name else (
            "native" if self._process and (data_dir / "hub-bin").exists() else "process"
        )

        return HubStatus(
            running=running,
            pid=pid,
            port=self.config.local_hub_port,
            url=f"http://localhost:{self.config.local_hub_port}",
            mode=mode if running else "unknown",
            started_at=None,
            logs_tail=logs_tail,
        )

    def wait_until_healthy(self, timeout: int = 120) -> bool:
        """等待 Hub 健康检查通过"""
        from .client import EigenFluxClient
        import copy
        cfg = copy.deepcopy(self.config)
        cfg.hub_url = f"http://localhost:{self.config.local_hub_port}"
        client = EigenFluxClient(cfg)

        start = time.time()
        while time.time() - start < timeout:
            try:
                if client.health_check():
                    return True
            except Exception:
                pass
            time.sleep(2)
        return False

    def switch_to_local_hub(self) -> None:
        """将全局配置切换为连接本地 Hub"""
        self.config.hub_url = f"http://localhost:{self.config.local_hub_port}"
        self.config.local_hub_mode = True
        self.config.ensure_dirs()
