"""
理科公式数据导入脚本
包含数学、物理、化学、生物等学科的常用公式
"""

import json
import time
import os
from database_schema import SCHEMA
from database_schema_base import EnhancedDatabaseManager


FORMULA_CATEGORIES = [
    # 数学分类
    {"category_id": "math_algebra", "name": "代数", "subject": "math", "parent_id": None, "sort_order": 1},
    {"category_id": "math_geometry", "name": "几何", "subject": "math", "parent_id": None, "sort_order": 2},
    {"category_id": "math_trigonometry", "name": "三角", "subject": "math", "parent_id": None, "sort_order": 3},
    {"category_id": "math_calculus", "name": "微积分", "subject": "math", "parent_id": None, "sort_order": 4},
    {"category_id": "math_probability", "name": "概率统计", "subject": "math", "parent_id": None, "sort_order": 5},
    {"category_id": "math_sequence", "name": "数列", "subject": "math", "parent_id": None, "sort_order": 6},
    {"category_id": "math_logarithm", "name": "对数指数", "subject": "math", "parent_id": None, "sort_order": 7},
    
    # 物理分类
    {"category_id": "physics_mechanics", "name": "力学", "subject": "physics", "parent_id": None, "sort_order": 1},
    {"category_id": "physics_electricity", "name": "电学", "subject": "physics", "parent_id": None, "sort_order": 2},
    {"category_id": "physics_thermodynamics", "name": "热学", "subject": "physics", "parent_id": None, "sort_order": 3},
    {"category_id": "physics_optics", "name": "光学", "subject": "physics", "parent_id": None, "sort_order": 4},
    {"category_id": "physics_waves", "name": "波动", "subject": "physics", "parent_id": None, "sort_order": 5},
    {"category_id": "physics_modern", "name": "近代物理", "subject": "physics", "parent_id": None, "sort_order": 6},
    
    # 化学分类
    {"category_id": "chemistry_inorganic", "name": "无机化学", "subject": "chemistry", "parent_id": None, "sort_order": 1},
    {"category_id": "chemistry_organic", "name": "有机化学", "subject": "chemistry", "parent_id": None, "sort_order": 2},
    {"category_id": "chemistry_physical", "name": "物理化学", "subject": "chemistry", "parent_id": None, "sort_order": 3},
    {"category_id": "chemistry_analytical", "name": "分析化学", "subject": "chemistry", "parent_id": None, "sort_order": 4},
    
    # 生物分类
    {"category_id": "biology_cell", "name": "细胞生物学", "subject": "biology", "parent_id": None, "sort_order": 1},
    {"category_id": "biology_genetics", "name": "遗传学", "subject": "biology", "parent_id": None, "sort_order": 2},
    {"category_id": "biology_molecular", "name": "分子生物学", "subject": "biology", "parent_id": None, "sort_order": 3},
]


SCIENCE_FORMULAS = [
    # ==================== 数学 - 代数 ====================
    {
        "formula_id": "math_quadratic",
        "name": "一元二次方程求根公式",
        "subject": "math",
        "category": "math_algebra",
        "subcategory": "quadratic_equations",
        "formula_latex": "x = \\frac{-b \\pm \\sqrt{b^2 - 4ac}}{2a}",
        "formula_plain": "x = (-b ± √(b² - 4ac)) / 2a",
        "description": "求解一元二次方程 ax² + bx + c = 0 的根",
        "variables": json.dumps({"a": "二次项系数", "b": "一次项系数", "c": "常数项", "x": "未知数"}),
        "units": json.dumps({}),
        "applications": "求解二次函数零点、抛物线与x轴交点",
        "grade_level": "初中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["方程", "求根", "初中数学"])
    },
    {
        "formula_id": "math_sum_squares",
        "name": "平方和公式",
        "subject": "math",
        "category": "math_algebra",
        "subcategory": "sum_formulas",
        "formula_latex": "(a + b)^2 = a^2 + 2ab + b^2",
        "formula_plain": "(a + b)² = a² + 2ab + b²",
        "description": "两数和的平方展开式",
        "variables": json.dumps({"a": "第一个数", "b": "第二个数"}),
        "units": json.dumps({}),
        "applications": "代数运算、因式分解",
        "grade_level": "初中",
        "difficulty": 1,
        "is_important": 1,
        "tags": json.dumps(["代数", "平方", "公式"])
    },
    {
        "formula_id": "math_diff_squares",
        "name": "平方差公式",
        "subject": "math",
        "category": "math_algebra",
        "subcategory": "difference_formulas",
        "formula_latex": "a^2 - b^2 = (a + b)(a - b)",
        "formula_plain": "a² - b² = (a + b)(a - b)",
        "description": "两数平方差的因式分解",
        "variables": json.dumps({"a": "第一个数", "b": "第二个数"}),
        "units": json.dumps({}),
        "applications": "代数运算、因式分解",
        "grade_level": "初中",
        "difficulty": 1,
        "is_important": 1,
        "tags": json.dumps(["代数", "因式分解"])
    },
    {
        "formula_id": "math_sum_cubes",
        "name": "立方和公式",
        "subject": "math",
        "category": "math_algebra",
        "subcategory": "sum_formulas",
        "formula_latex": "a^3 + b^3 = (a + b)(a^2 - ab + b^2)",
        "formula_plain": "a³ + b³ = (a + b)(a² - ab + b²)",
        "description": "两数立方和的因式分解",
        "variables": json.dumps({"a": "第一个数", "b": "第二个数"}),
        "units": json.dumps({}),
        "applications": "代数运算",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 0,
        "tags": json.dumps(["代数", "立方"])
    },
    {
        "formula_id": "math_diff_cubes",
        "name": "立方差公式",
        "subject": "math",
        "category": "math_algebra",
        "subcategory": "difference_formulas",
        "formula_latex": "a^3 - b^3 = (a - b)(a^2 + ab + b^2)",
        "formula_plain": "a³ - b³ = (a - b)(a² + ab + b²)",
        "description": "两数立方差的因式分解",
        "variables": json.dumps({"a": "第一个数", "b": "第二个数"}),
        "units": json.dumps({}),
        "applications": "代数运算",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 0,
        "tags": json.dumps(["代数", "立方"])
    },
    {
        "formula_id": "math_binomial",
        "name": "二项式定理",
        "subject": "math",
        "category": "math_algebra",
        "subcategory": "binomial_theorem",
        "formula_latex": "(a + b)^n = \\sum_{k=0}^{n} \\binom{n}{k} a^{n-k} b^k",
        "formula_plain": "(a + b)^n = Σ C(n,k) * a^(n-k) * b^k",
        "description": "二项式展开定理",
        "variables": json.dumps({"a": "第一项", "b": "第二项", "n": "指数", "k": "项数"}),
        "units": json.dumps({}),
        "applications": "多项式展开、概率计算",
        "grade_level": "高中",
        "difficulty": 4,
        "is_important": 1,
        "tags": json.dumps(["代数", "二项式"])
    },
    
    # ==================== 数学 - 几何 ====================
    {
        "formula_id": "math_circle_area",
        "name": "圆的面积公式",
        "subject": "math",
        "category": "math_geometry",
        "subcategory": "circle",
        "formula_latex": "S = \\pi r^2",
        "formula_plain": "S = πr²",
        "description": "计算圆的面积",
        "variables": json.dumps({"S": "面积", "r": "半径", "π": "圆周率约3.1416"}),
        "units": json.dumps({"S": "平方单位", "r": "长度单位"}),
        "applications": "计算圆形面积、周长相关问题",
        "grade_level": "小学",
        "difficulty": 1,
        "is_important": 1,
        "tags": json.dumps(["几何", "圆", "面积"])
    },
    {
        "formula_id": "math_circle_circumference",
        "name": "圆的周长公式",
        "subject": "math",
        "category": "math_geometry",
        "subcategory": "circle",
        "formula_latex": "C = 2\\pi r = \\pi d",
        "formula_plain": "C = 2πr = πd",
        "description": "计算圆的周长",
        "variables": json.dumps({"C": "周长", "r": "半径", "d": "直径", "π": "圆周率"}),
        "units": json.dumps({"C": "长度单位", "r": "长度单位", "d": "长度单位"}),
        "applications": "计算圆形周长",
        "grade_level": "小学",
        "difficulty": 1,
        "is_important": 1,
        "tags": json.dumps(["几何", "圆", "周长"])
    },
    {
        "formula_id": "math_triangle_area",
        "name": "三角形面积公式",
        "subject": "math",
        "category": "math_geometry",
        "subcategory": "triangle",
        "formula_latex": "S = \\frac{1}{2} bh",
        "formula_plain": "S = (1/2)bh",
        "description": "计算三角形面积",
        "variables": json.dumps({"S": "面积", "b": "底边长", "h": "高"}),
        "units": json.dumps({"S": "平方单位", "b": "长度单位", "h": "长度单位"}),
        "applications": "计算三角形面积",
        "grade_level": "小学",
        "difficulty": 1,
        "is_important": 1,
        "tags": json.dumps(["几何", "三角形", "面积"])
    },
    {
        "formula_id": "math_triangle_heron",
        "name": "海伦公式",
        "subject": "math",
        "category": "math_geometry",
        "subcategory": "triangle",
        "formula_latex": "S = \\sqrt{p(p-a)(p-b)(p-c)}, \\quad p = \\frac{a+b+c}{2}",
        "formula_plain": "S = √[p(p-a)(p-b)(p-c)], p = (a+b+c)/2",
        "description": "已知三边长求三角形面积",
        "variables": json.dumps({"S": "面积", "a": "边长", "b": "边长", "c": "边长", "p": "半周长"}),
        "units": json.dumps({"S": "平方单位", "a,b,c": "长度单位"}),
        "applications": "已知三边求面积",
        "grade_level": "初中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["几何", "三角形", "海伦"])
    },
    {
        "formula_id": "math_pythagorean",
        "name": "勾股定理",
        "subject": "math",
        "category": "math_geometry",
        "subcategory": "triangle",
        "formula_latex": "a^2 + b^2 = c^2",
        "formula_plain": "a² + b² = c²",
        "description": "直角三角形两直角边平方和等于斜边平方",
        "variables": json.dumps({"a": "直角边", "b": "直角边", "c": "斜边"}),
        "units": json.dumps({"a,b,c": "长度单位"}),
        "applications": "直角三角形边长计算",
        "grade_level": "初中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["几何", "三角形", "勾股"])
    },
    {
        "formula_id": "math_rectangle_area",
        "name": "矩形面积公式",
        "subject": "math",
        "category": "math_geometry",
        "subcategory": "rectangle",
        "formula_latex": "S = ab",
        "formula_plain": "S = ab",
        "description": "计算矩形面积",
        "variables": json.dumps({"S": "面积", "a": "长", "b": "宽"}),
        "units": json.dumps({"S": "平方单位", "a": "长度单位", "b": "长度单位"}),
        "applications": "计算长方形面积",
        "grade_level": "小学",
        "difficulty": 1,
        "is_important": 1,
        "tags": json.dumps(["几何", "矩形", "面积"])
    },
    {
        "formula_id": "math_trapezoid_area",
        "name": "梯形面积公式",
        "subject": "math",
        "category": "math_geometry",
        "subcategory": "trapezoid",
        "formula_latex": "S = \\frac{1}{2}(a + b)h",
        "formula_plain": "S = (1/2)(a + b)h",
        "description": "计算梯形面积",
        "variables": json.dumps({"S": "面积", "a": "上底", "b": "下底", "h": "高"}),
        "units": json.dumps({"S": "平方单位", "a,b": "长度单位", "h": "长度单位"}),
        "applications": "计算梯形面积",
        "grade_level": "小学",
        "difficulty": 1,
        "is_important": 1,
        "tags": json.dumps(["几何", "梯形", "面积"])
    },
    {
        "formula_id": "math_sphere_volume",
        "name": "球体体积公式",
        "subject": "math",
        "category": "math_geometry",
        "subcategory": "sphere",
        "formula_latex": "V = \\frac{4}{3}\\pi r^3",
        "formula_plain": "V = (4/3)πr³",
        "description": "计算球体体积",
        "variables": json.dumps({"V": "体积", "r": "半径", "π": "圆周率"}),
        "units": json.dumps({"V": "立方单位", "r": "长度单位"}),
        "applications": "计算球体体积",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["几何", "球体", "体积"])
    },
    {
        "formula_id": "math_sphere_surface",
        "name": "球体表面积公式",
        "subject": "math",
        "category": "math_geometry",
        "subcategory": "sphere",
        "formula_latex": "S = 4\\pi r^2",
        "formula_plain": "S = 4πr²",
        "description": "计算球体表面积",
        "variables": json.dumps({"S": "表面积", "r": "半径", "π": "圆周率"}),
        "units": json.dumps({"S": "平方单位", "r": "长度单位"}),
        "applications": "计算球体表面积",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["几何", "球体", "表面积"])
    },
    {
        "formula_id": "math_cylinder_volume",
        "name": "圆柱体积公式",
        "subject": "math",
        "category": "math_geometry",
        "subcategory": "cylinder",
        "formula_latex": "V = \\pi r^2 h",
        "formula_plain": "V = πr²h",
        "description": "计算圆柱体积",
        "variables": json.dumps({"V": "体积", "r": "底面半径", "h": "高", "π": "圆周率"}),
        "units": json.dumps({"V": "立方单位", "r": "长度单位", "h": "长度单位"}),
        "applications": "计算圆柱体积",
        "grade_level": "初中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["几何", "圆柱", "体积"])
    },
    {
        "formula_id": "math_cone_volume",
        "name": "圆锥体积公式",
        "subject": "math",
        "category": "math_geometry",
        "subcategory": "cone",
        "formula_latex": "V = \\frac{1}{3}\\pi r^2 h",
        "formula_plain": "V = (1/3)πr²h",
        "description": "计算圆锥体积",
        "variables": json.dumps({"V": "体积", "r": "底面半径", "h": "高", "π": "圆周率"}),
        "units": json.dumps({"V": "立方单位", "r": "长度单位", "h": "长度单位"}),
        "applications": "计算圆锥体积",
        "grade_level": "初中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["几何", "圆锥", "体积"])
    },
    
    # ==================== 数学 - 三角 ====================
    {
        "formula_id": "math_sin_def",
        "name": "正弦定义",
        "subject": "math",
        "category": "math_trigonometry",
        "subcategory": "basic_definitions",
        "formula_latex": "\\sin \\theta = \\frac{\\text{对边}}{\\text{斜边}}",
        "formula_plain": "sinθ = 对边/斜边",
        "description": "直角三角形中正弦函数定义",
        "variables": json.dumps({"θ": "角度", "对边": "角θ的对边", "斜边": "直角三角形斜边"}),
        "units": json.dumps({}),
        "applications": "三角函数计算",
        "grade_level": "初中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["三角", "正弦"])
    },
    {
        "formula_id": "math_cos_def",
        "name": "余弦定义",
        "subject": "math",
        "category": "math_trigonometry",
        "subcategory": "basic_definitions",
        "formula_latex": "\\cos \\theta = \\frac{\\text{邻边}}{\\text{斜边}}",
        "formula_plain": "cosθ = 邻边/斜边",
        "description": "直角三角形中余弦函数定义",
        "variables": json.dumps({"θ": "角度", "邻边": "角θ的邻边", "斜边": "直角三角形斜边"}),
        "units": json.dumps({}),
        "applications": "三角函数计算",
        "grade_level": "初中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["三角", "余弦"])
    },
    {
        "formula_id": "math_tan_def",
        "name": "正切定义",
        "subject": "math",
        "category": "math_trigonometry",
        "subcategory": "basic_definitions",
        "formula_latex": "\\tan \\theta = \\frac{\\text{对边}}{\\text{邻边}}",
        "formula_plain": "tanθ = 对边/邻边",
        "description": "直角三角形中正切函数定义",
        "variables": json.dumps({"θ": "角度", "对边": "角θ的对边", "邻边": "角θ的邻边"}),
        "units": json.dumps({}),
        "applications": "三角函数计算",
        "grade_level": "初中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["三角", "正切"])
    },
    {
        "formula_id": "math_sin_cos_identity",
        "name": "同角三角函数关系",
        "subject": "math",
        "category": "math_trigonometry",
        "subcategory": "identities",
        "formula_latex": "\\sin^2 \\theta + \\cos^2 \\theta = 1",
        "formula_plain": "sin²θ + cos²θ = 1",
        "description": "同角正弦余弦平方和等于1",
        "variables": json.dumps({"θ": "角度"}),
        "units": json.dumps({}),
        "applications": "三角函数恒等变换",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["三角", "恒等式"])
    },
    {
        "formula_id": "math_sin_addition",
        "name": "正弦加法公式",
        "subject": "math",
        "category": "math_trigonometry",
        "subcategory": "addition_formulas",
        "formula_latex": "\\sin(A + B) = \\sin A \\cos B + \\cos A \\sin B",
        "formula_plain": "sin(A+B) = sinAcosB + cosAsinB",
        "description": "两角和的正弦公式",
        "variables": json.dumps({"A": "角度A", "B": "角度B"}),
        "units": json.dumps({}),
        "applications": "三角函数恒等变换",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["三角", "和角"])
    },
    {
        "formula_id": "math_cos_addition",
        "name": "余弦加法公式",
        "subject": "math",
        "category": "math_trigonometry",
        "subcategory": "addition_formulas",
        "formula_latex": "\\cos(A + B) = \\cos A \\cos B - \\sin A \\sin B",
        "formula_plain": "cos(A+B) = cosAcosB - sinAsinB",
        "description": "两角和的余弦公式",
        "variables": json.dumps({"A": "角度A", "B": "角度B"}),
        "units": json.dumps({}),
        "applications": "三角函数恒等变换",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["三角", "和角"])
    },
    {
        "formula_id": "math_sin_double",
        "name": "正弦二倍角公式",
        "subject": "math",
        "category": "math_trigonometry",
        "subcategory": "double_angle",
        "formula_latex": "\\sin 2\\theta = 2\\sin \\theta \\cos \\theta",
        "formula_plain": "sin2θ = 2sinθcosθ",
        "description": "二倍角正弦公式",
        "variables": json.dumps({"θ": "角度"}),
        "units": json.dumps({}),
        "applications": "三角函数恒等变换",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["三角", "二倍角"])
    },
    {
        "formula_id": "math_cos_double",
        "name": "余弦二倍角公式",
        "subject": "math",
        "category": "math_trigonometry",
        "subcategory": "double_angle",
        "formula_latex": "\\cos 2\\theta = \\cos^2 \\theta - \\sin^2 \\theta = 2\\cos^2 \\theta - 1 = 1 - 2\\sin^2 \\theta",
        "formula_plain": "cos2θ = cos²θ - sin²θ = 2cos²θ - 1 = 1 - 2sin²θ",
        "description": "二倍角余弦公式（三种形式）",
        "variables": json.dumps({"θ": "角度"}),
        "units": json.dumps({}),
        "applications": "三角函数恒等变换",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["三角", "二倍角"])
    },
    
    # ==================== 数学 - 微积分 ====================
    {
        "formula_id": "math_derivative_power",
        "name": "幂函数导数公式",
        "subject": "math",
        "category": "math_calculus",
        "subcategory": "derivatives",
        "formula_latex": "\\frac{d}{dx} x^n = nx^{n-1}",
        "formula_plain": "d/dx x^n = nx^(n-1)",
        "description": "幂函数的导数",
        "variables": json.dumps({"x": "自变量", "n": "常数"}),
        "units": json.dumps({}),
        "applications": "求导计算",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["微积分", "导数"])
    },
    {
        "formula_id": "math_derivative_sin",
        "name": "正弦函数导数",
        "subject": "math",
        "category": "math_calculus",
        "subcategory": "derivatives",
        "formula_latex": "\\frac{d}{dx} \\sin x = \\cos x",
        "formula_plain": "d/dx sinx = cosx",
        "description": "正弦函数的导数",
        "variables": json.dumps({"x": "自变量"}),
        "units": json.dumps({}),
        "applications": "求导计算",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["微积分", "导数"])
    },
    {
        "formula_id": "math_derivative_cos",
        "name": "余弦函数导数",
        "subject": "math",
        "category": "math_calculus",
        "subcategory": "derivatives",
        "formula_latex": "\\frac{d}{dx} \\cos x = -\\sin x",
        "formula_plain": "d/dx cosx = -sinx",
        "description": "余弦函数的导数",
        "variables": json.dumps({"x": "自变量"}),
        "units": json.dumps({}),
        "applications": "求导计算",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["微积分", "导数"])
    },
    {
        "formula_id": "math_derivative_exponential",
        "name": "指数函数导数",
        "subject": "math",
        "category": "math_calculus",
        "subcategory": "derivatives",
        "formula_latex": "\\frac{d}{dx} e^x = e^x",
        "formula_plain": "d/dx e^x = e^x",
        "description": "自然指数函数的导数",
        "variables": json.dumps({"x": "自变量", "e": "自然常数约2.718"}),
        "units": json.dumps({}),
        "applications": "求导计算",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["微积分", "导数", "指数"])
    },
    {
        "formula_id": "math_integral_power",
        "name": "幂函数积分公式",
        "subject": "math",
        "category": "math_calculus",
        "subcategory": "integrals",
        "formula_latex": "\\int x^n dx = \\frac{x^{n+1}}{n+1} + C \\quad (n \\neq -1)",
        "formula_plain": "∫x^n dx = x^(n+1)/(n+1) + C",
        "description": "幂函数的不定积分",
        "variables": json.dumps({"x": "自变量", "n": "常数", "C": "积分常数"}),
        "units": json.dumps({}),
        "applications": "积分计算",
        "grade_level": "高中",
        "difficulty": 4,
        "is_important": 1,
        "tags": json.dumps(["微积分", "积分"])
    },
    {
        "formula_id": "math_integral_sin",
        "name": "正弦函数积分",
        "subject": "math",
        "category": "math_calculus",
        "subcategory": "integrals",
        "formula_latex": "\\int \\sin x dx = -\\cos x + C",
        "formula_plain": "∫sinx dx = -cosx + C",
        "description": "正弦函数的不定积分",
        "variables": json.dumps({"x": "自变量", "C": "积分常数"}),
        "units": json.dumps({}),
        "applications": "积分计算",
        "grade_level": "高中",
        "difficulty": 4,
        "is_important": 1,
        "tags": json.dumps(["微积分", "积分"])
    },
    {
        "formula_id": "math_integral_cos",
        "name": "余弦函数积分",
        "subject": "math",
        "category": "math_calculus",
        "subcategory": "integrals",
        "formula_latex": "\\int \\cos x dx = \\sin x + C",
        "formula_plain": "∫cosx dx = sinx + C",
        "description": "余弦函数的不定积分",
        "variables": json.dumps({"x": "自变量", "C": "积分常数"}),
        "units": json.dumps({}),
        "applications": "积分计算",
        "grade_level": "高中",
        "difficulty": 4,
        "is_important": 1,
        "tags": json.dumps(["微积分", "积分"])
    },
    {
        "formula_id": "math_integral_exponential",
        "name": "指数函数积分",
        "subject": "math",
        "category": "math_calculus",
        "subcategory": "integrals",
        "formula_latex": "\\int e^x dx = e^x + C",
        "formula_plain": "∫e^x dx = e^x + C",
        "description": "自然指数函数的不定积分",
        "variables": json.dumps({"x": "自变量", "e": "自然常数", "C": "积分常数"}),
        "units": json.dumps({}),
        "applications": "积分计算",
        "grade_level": "高中",
        "difficulty": 4,
        "is_important": 1,
        "tags": json.dumps(["微积分", "积分", "指数"])
    },
    
    # ==================== 数学 - 概率统计 ====================
    {
        "formula_id": "math_mean",
        "name": "平均数公式",
        "subject": "math",
        "category": "math_probability",
        "subcategory": "statistics",
        "formula_latex": "\\bar{x} = \\frac{1}{n} \\sum_{i=1}^{n} x_i",
        "formula_plain": "x̄ = (1/n)Σx_i",
        "description": "算术平均数计算公式",
        "variables": json.dumps({"x̄": "平均数", "n": "数据个数", "x_i": "第i个数据"}),
        "units": json.dumps({}),
        "applications": "数据分析",
        "grade_level": "初中",
        "difficulty": 1,
        "is_important": 1,
        "tags": json.dumps(["统计", "平均数"])
    },
    {
        "formula_id": "math_variance",
        "name": "方差公式",
        "subject": "math",
        "category": "math_probability",
        "subcategory": "statistics",
        "formula_latex": "s^2 = \\frac{1}{n-1} \\sum_{i=1}^{n} (x_i - \\bar{x})^2",
        "formula_plain": "s² = (1/(n-1))Σ(x_i - x̄)²",
        "description": "样本方差计算公式",
        "variables": json.dumps({"s²": "方差", "n": "数据个数", "x_i": "第i个数据", "x̄": "平均数"}),
        "units": json.dumps({}),
        "applications": "数据分析",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["统计", "方差"])
    },
    {
        "formula_id": "math_standard_deviation",
        "name": "标准差公式",
        "subject": "math",
        "category": "math_probability",
        "subcategory": "statistics",
        "formula_latex": "s = \\sqrt{\\frac{1}{n-1} \\sum_{i=1}^{n} (x_i - \\bar{x})^2}",
        "formula_plain": "s = √[(1/(n-1))Σ(x_i - x̄)²]",
        "description": "样本标准差计算公式",
        "variables": json.dumps({"s": "标准差", "n": "数据个数", "x_i": "第i个数据", "x̄": "平均数"}),
        "units": json.dumps({}),
        "applications": "数据分析",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["统计", "标准差"])
    },
    {
        "formula_id": "math_combination",
        "name": "组合公式",
        "subject": "math",
        "category": "math_probability",
        "subcategory": "combinations",
        "formula_latex": "\\binom{n}{k} = \\frac{n!}{k!(n-k)!}",
        "formula_plain": "C(n,k) = n!/(k!(n-k)!)",
        "description": "从n个元素中选k个的组合数",
        "variables": json.dumps({"n": "总数", "k": "选取数", "!": "阶乘"}),
        "units": json.dumps({}),
        "applications": "概率计算",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["概率", "组合"])
    },
    {
        "formula_id": "math_permutation",
        "name": "排列公式",
        "subject": "math",
        "category": "math_probability",
        "subcategory": "permutations",
        "formula_latex": "P(n,k) = \\frac{n!}{(n-k)!}",
        "formula_plain": "P(n,k) = n!/(n-k)!",
        "description": "从n个元素中选k个的排列数",
        "variables": json.dumps({"n": "总数", "k": "选取数", "!": "阶乘"}),
        "units": json.dumps({}),
        "applications": "概率计算",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["概率", "排列"])
    },
    
    # ==================== 数学 - 数列 ====================
    {
        "formula_id": "math_arithmetic_sum",
        "name": "等差数列求和公式",
        "subject": "math",
        "category": "math_sequence",
        "subcategory": "arithmetic",
        "formula_latex": "S_n = \\frac{n}{2}(a_1 + a_n) = \\frac{n}{2}[2a_1 + (n-1)d]",
        "formula_plain": "S_n = (n/2)(a₁ + a_n) = (n/2)[2a₁ + (n-1)d]",
        "description": "等差数列前n项和",
        "variables": json.dumps({"S_n": "前n项和", "n": "项数", "a₁": "首项", "a_n": "第n项", "d": "公差"}),
        "units": json.dumps({}),
        "applications": "数列求和",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["数列", "等差"])
    },
    {
        "formula_id": "math_arithmetic_nth",
        "name": "等差数列通项公式",
        "subject": "math",
        "category": "math_sequence",
        "subcategory": "arithmetic",
        "formula_latex": "a_n = a_1 + (n-1)d",
        "formula_plain": "a_n = a₁ + (n-1)d",
        "description": "等差数列第n项",
        "variables": json.dumps({"a_n": "第n项", "a₁": "首项", "n": "项数", "d": "公差"}),
        "units": json.dumps({}),
        "applications": "数列计算",
        "grade_level": "高中",
        "difficulty": 1,
        "is_important": 1,
        "tags": json.dumps(["数列", "等差"])
    },
    {
        "formula_id": "math_geometric_sum",
        "name": "等比数列求和公式",
        "subject": "math",
        "category": "math_sequence",
        "subcategory": "geometric",
        "formula_latex": "S_n = a_1 \\frac{1-q^n}{1-q} \\quad (q \\neq 1)",
        "formula_plain": "S_n = a₁(1-q^n)/(1-q)",
        "description": "等比数列前n项和",
        "variables": json.dumps({"S_n": "前n项和", "a₁": "首项", "q": "公比", "n": "项数"}),
        "units": json.dumps({}),
        "applications": "数列求和",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["数列", "等比"])
    },
    {
        "formula_id": "math_geometric_nth",
        "name": "等比数列通项公式",
        "subject": "math",
        "category": "math_sequence",
        "subcategory": "geometric",
        "formula_latex": "a_n = a_1 q^{n-1}",
        "formula_plain": "a_n = a₁ q^(n-1)",
        "description": "等比数列第n项",
        "variables": json.dumps({"a_n": "第n项", "a₁": "首项", "q": "公比", "n": "项数"}),
        "units": json.dumps({}),
        "applications": "数列计算",
        "grade_level": "高中",
        "difficulty": 1,
        "is_important": 1,
        "tags": json.dumps(["数列", "等比"])
    },
    
    # ==================== 数学 - 对数指数 ====================
    {
        "formula_id": "math_log_def",
        "name": "对数定义",
        "subject": "math",
        "category": "math_logarithm",
        "subcategory": "definitions",
        "formula_latex": "\\log_b a = c \\iff b^c = a",
        "formula_plain": "log_b a = c <=> b^c = a",
        "description": "对数与指数的关系",
        "variables": json.dumps({"b": "底数", "a": "真数", "c": "对数值"}),
        "units": json.dumps({}),
        "applications": "对数计算",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["对数", "指数"])
    },
    {
        "formula_id": "math_log_product",
        "name": "对数乘法法则",
        "subject": "math",
        "category": "math_logarithm",
        "subcategory": "laws",
        "formula_latex": "\\log_b(xy) = \\log_b x + \\log_b y",
        "formula_plain": "log_b(xy) = log_b x + log_b y",
        "description": "积的对数等于对数之和",
        "variables": json.dumps({"b": "底数", "x": "真数1", "y": "真数2"}),
        "units": json.dumps({}),
        "applications": "对数运算",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["对数", "法则"])
    },
    {
        "formula_id": "math_log_quotient",
        "name": "对数除法法则",
        "subject": "math",
        "category": "math_logarithm",
        "subcategory": "laws",
        "formula_latex": "\\log_b\\left(\\frac{x}{y}\\right) = \\log_b x - \\log_b y",
        "formula_plain": "log_b(x/y) = log_b x - log_b y",
        "description": "商的对数等于对数之差",
        "variables": json.dumps({"b": "底数", "x": "被除数", "y": "除数"}),
        "units": json.dumps({}),
        "applications": "对数运算",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["对数", "法则"])
    },
    {
        "formula_id": "math_log_power",
        "name": "对数幂法则",
        "subject": "math",
        "category": "math_logarithm",
        "subcategory": "laws",
        "formula_latex": "\\log_b x^n = n \\log_b x",
        "formula_plain": "log_b x^n = n log_b x",
        "description": "幂的对数等于指数乘对数",
        "variables": json.dumps({"b": "底数", "x": "真数", "n": "指数"}),
        "units": json.dumps({}),
        "applications": "对数运算",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["对数", "法则"])
    },
    
    # ==================== 物理 - 力学 ====================
    {
        "formula_id": "phy_newton_second",
        "name": "牛顿第二定律",
        "subject": "physics",
        "category": "physics_mechanics",
        "subcategory": "newton_laws",
        "formula_latex": "F = ma",
        "formula_plain": "F = ma",
        "description": "物体加速度与所受合外力成正比",
        "variables": json.dumps({"F": "合外力", "m": "质量", "a": "加速度"}),
        "units": json.dumps({"F": "N", "m": "kg", "a": "m/s²"}),
        "applications": "力与运动问题",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["力学", "牛顿定律"])
    },
    {
        "formula_id": "phy_gravity",
        "name": "万有引力定律",
        "subject": "physics",
        "category": "physics_mechanics",
        "subcategory": "gravity",
        "formula_latex": "F = G \\frac{m_1 m_2}{r^2}",
        "formula_plain": "F = G m₁m₂/r²",
        "description": "两物体间的万有引力",
        "variables": json.dumps({"F": "万有引力", "G": "引力常量6.67×10⁻¹¹", "m₁": "质量1", "m₂": "质量2", "r": "距离"}),
        "units": json.dumps({"F": "N", "m₁,m₂": "kg", "r": "m"}),
        "applications": "天体运动",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["力学", "万有引力"])
    },
    {
        "formula_id": "phy_kinematic",
        "name": "匀变速直线运动公式",
        "subject": "physics",
        "category": "physics_mechanics",
        "subcategory": "kinematics",
        "formula_latex": "v = v_0 + at, \\quad s = v_0 t + \\frac{1}{2}at^2, \\quad v^2 = v_0^2 + 2as",
        "formula_plain": "v = v₀ + at, s = v₀t + (1/2)at², v² = v₀² + 2as",
        "description": "匀变速直线运动速度、位移公式",
        "variables": json.dumps({"v": "末速度", "v₀": "初速度", "a": "加速度", "t": "时间", "s": "位移"}),
        "units": json.dumps({"v,v₀": "m/s", "a": "m/s²", "t": "s", "s": "m"}),
        "applications": "运动学问题",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["力学", "运动学"])
    },
    {
        "formula_id": "phy_work",
        "name": "功的公式",
        "subject": "physics",
        "category": "physics_mechanics",
        "subcategory": "energy",
        "formula_latex": "W = Fs\\cos\\theta",
        "formula_plain": "W = Fscosθ",
        "description": "力对物体做的功",
        "variables": json.dumps({"W": "功", "F": "力", "s": "位移", "θ": "力与位移夹角"}),
        "units": json.dumps({"W": "J", "F": "N", "s": "m"}),
        "applications": "能量问题",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["力学", "功"])
    },
    {
        "formula_id": "phy_kinetic_energy",
        "name": "动能公式",
        "subject": "physics",
        "category": "physics_mechanics",
        "subcategory": "energy",
        "formula_latex": "E_k = \\frac{1}{2}mv^2",
        "formula_plain": "E_k = (1/2)mv²",
        "description": "物体的动能",
        "variables": json.dumps({"E_k": "动能", "m": "质量", "v": "速度"}),
        "units": json.dumps({"E_k": "J", "m": "kg", "v": "m/s"}),
        "applications": "能量守恒",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["力学", "动能"])
    },
    {
        "formula_id": "phy_potential_energy",
        "name": "重力势能公式",
        "subject": "physics",
        "category": "physics_mechanics",
        "subcategory": "energy",
        "formula_latex": "E_p = mgh",
        "formula_plain": "E_p = mgh",
        "description": "物体的重力势能",
        "variables": json.dumps({"E_p": "重力势能", "m": "质量", "g": "重力加速度9.8m/s²", "h": "高度"}),
        "units": json.dumps({"E_p": "J", "m": "kg", "g": "m/s²", "h": "m"}),
        "applications": "能量守恒",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["力学", "势能"])
    },
    {
        "formula_id": "phy_momentum",
        "name": "动量公式",
        "subject": "physics",
        "category": "physics_mechanics",
        "subcategory": "momentum",
        "formula_latex": "p = mv",
        "formula_plain": "p = mv",
        "description": "物体的动量",
        "variables": json.dumps({"p": "动量", "m": "质量", "v": "速度"}),
        "units": json.dumps({"p": "kg·m/s", "m": "kg", "v": "m/s"}),
        "applications": "动量守恒",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["力学", "动量"])
    },
    {
        "formula_id": "phy_momentum_conservation",
        "name": "动量守恒定律",
        "subject": "physics",
        "category": "physics_mechanics",
        "subcategory": "momentum",
        "formula_latex": "m_1 v_1 + m_2 v_2 = m_1 v_1' + m_2 v_2'",
        "formula_plain": "m₁v₁ + m₂v₂ = m₁v₁' + m₂v₂'",
        "description": "系统动量守恒",
        "variables": json.dumps({"m₁,m₂": "质量", "v₁,v₂": "碰撞前速度", "v₁',v₂'": "碰撞后速度"}),
        "units": json.dumps({"m": "kg", "v": "m/s"}),
        "applications": "碰撞问题",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["力学", "动量守恒"])
    },
    {
        "formula_id": "phy_hooke",
        "name": "胡克定律",
        "subject": "physics",
        "category": "physics_mechanics",
        "subcategory": "elasticity",
        "formula_latex": "F = -kx",
        "formula_plain": "F = -kx",
        "description": "弹簧弹力与形变量成正比",
        "variables": json.dumps({"F": "弹力", "k": "劲度系数", "x": "形变量"}),
        "units": json.dumps({"F": "N", "k": "N/m", "x": "m"}),
        "applications": "弹簧问题",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["力学", "胡克定律"])
    },
    
    # ==================== 物理 - 电学 ====================
    {
        "formula_id": "phy_ohm",
        "name": "欧姆定律",
        "subject": "physics",
        "category": "physics_electricity",
        "subcategory": "circuits",
        "formula_latex": "I = \\frac{U}{R}",
        "formula_plain": "I = U/R",
        "description": "电流与电压成正比，与电阻成反比",
        "variables": json.dumps({"I": "电流", "U": "电压", "R": "电阻"}),
        "units": json.dumps({"I": "A", "U": "V", "R": "Ω"}),
        "applications": "电路计算",
        "grade_level": "初中",
        "difficulty": 1,
        "is_important": 1,
        "tags": json.dumps(["电学", "欧姆定律"])
    },
    {
        "formula_id": "phy_resistance",
        "name": "电阻定律",
        "subject": "physics",
        "category": "physics_electricity",
        "subcategory": "circuits",
        "formula_latex": "R = \\rho \\frac{L}{S}",
        "formula_plain": "R = ρL/S",
        "description": "电阻与材料电阻率、长度成正比，与横截面积成反比",
        "variables": json.dumps({"R": "电阻", "ρ": "电阻率", "L": "长度", "S": "横截面积"}),
        "units": json.dumps({"R": "Ω", "ρ": "Ω·m", "L": "m", "S": "m²"}),
        "applications": "电阻计算",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["电学", "电阻"])
    },
    {
        "formula_id": "phy_electric_power",
        "name": "电功率公式",
        "subject": "physics",
        "category": "physics_electricity",
        "subcategory": "power",
        "formula_latex": "P = UI = I^2R = \\frac{U^2}{R}",
        "formula_plain": "P = UI = I²R = U²/R",
        "description": "电功率计算公式",
        "variables": json.dumps({"P": "功率", "U": "电压", "I": "电流", "R": "电阻"}),
        "units": json.dumps({"P": "W", "U": "V", "I": "A", "R": "Ω"}),
        "applications": "电功率计算",
        "grade_level": "初中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["电学", "功率"])
    },
    {
        "formula_id": "phy_electric_energy",
        "name": "电功公式",
        "subject": "physics",
        "category": "physics_electricity",
        "subcategory": "energy",
        "formula_latex": "W = UIt = Pt",
        "formula_plain": "W = UIt = Pt",
        "description": "电流做的功",
        "variables": json.dumps({"W": "电功", "U": "电压", "I": "电流", "t": "时间", "P": "功率"}),
        "units": json.dumps({"W": "J", "U": "V", "I": "A", "t": "s", "P": "W"}),
        "applications": "电能计算",
        "grade_level": "初中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["电学", "电功"])
    },
    {
        "formula_id": "phy_coulomb",
        "name": "库仑定律",
        "subject": "physics",
        "category": "physics_electricity",
        "subcategory": "electrostatics",
        "formula_latex": "F = k \\frac{q_1 q_2}{r^2}",
        "formula_plain": "F = k q₁q₂/r²",
        "description": "两点电荷间的静电力",
        "variables": json.dumps({"F": "静电力", "k": "静电力常量9×10⁹", "q₁": "电荷1", "q₂": "电荷2", "r": "距离"}),
        "units": json.dumps({"F": "N", "q": "C", "r": "m"}),
        "applications": "静电问题",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["电学", "库仑定律"])
    },
    {
        "formula_id": "phy_gauss",
        "name": "高斯定律",
        "subject": "physics",
        "category": "physics_electricity",
        "subcategory": "electrostatics",
        "formula_latex": "\\oint \\vec{E} \\cdot d\\vec{S} = \\frac{q_{enclosed}}{\\epsilon_0}",
        "formula_plain": "∮E·dS = q/ε₀",
        "description": "电通量与闭合曲面内电荷的关系",
        "variables": json.dumps({"E": "电场强度", "S": "面积", "q": "包围电荷", "ε₀": "真空介电常数"}),
        "units": json.dumps({"E": "N/C", "S": "m²", "q": "C"}),
        "applications": "电场计算",
        "grade_level": "高中",
        "difficulty": 5,
        "is_important": 1,
        "tags": json.dumps(["电学", "高斯定律"])
    },
    {
        "formula_id": "phy_biot_savart",
        "name": "毕奥-萨伐尔定律",
        "subject": "physics",
        "category": "physics_electricity",
        "subcategory": "magnetism",
        "formula_latex": "dB = \\frac{\\mu_0}{4\\pi} \\frac{Idl \\sin\\theta}{r^2}",
        "formula_plain": "dB = (μ₀/4π)(Idl sinθ)/r²",
        "description": "电流元产生的磁感应强度",
        "variables": json.dumps({"dB": "磁感应强度", "μ₀": "真空磁导率", "I": "电流", "dl": "电流元长度", "θ": "夹角", "r": "距离"}),
        "units": json.dumps({"B": "T", "I": "A", "r": "m"}),
        "applications": "磁场计算",
        "grade_level": "高中",
        "difficulty": 5,
        "is_important": 0,
        "tags": json.dumps(["电学", "磁场"])
    },
    
    # ==================== 物理 - 热学 ====================
    {
        "formula_id": "phy_ideal_gas",
        "name": "理想气体状态方程",
        "subject": "physics",
        "category": "physics_thermodynamics",
        "subcategory": "gas_laws",
        "formula_latex": "PV = nRT",
        "formula_plain": "PV = nRT",
        "description": "理想气体压强、体积、温度关系",
        "variables": json.dumps({"P": "压强", "V": "体积", "n": "物质的量", "R": "气体常量", "T": "温度"}),
        "units": json.dumps({"P": "Pa", "V": "m³", "n": "mol", "T": "K"}),
        "applications": "气体问题",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["热学", "理想气体"])
    },
    {
        "formula_id": "phy_heat_conduction",
        "name": "热传导公式",
        "subject": "physics",
        "category": "physics_thermodynamics",
        "subcategory": "heat_transfer",
        "formula_latex": "Q = kA \\frac{\\Delta T}{d} t",
        "formula_plain": "Q = kA(ΔT/d)t",
        "description": "热传导速率",
        "variables": json.dumps({"Q": "热量", "k": "热导率", "A": "面积", "ΔT": "温度差", "d": "厚度", "t": "时间"}),
        "units": json.dumps({"Q": "J", "k": "W/(m·K)", "A": "m²", "T": "K", "d": "m", "t": "s"}),
        "applications": "热传导问题",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 0,
        "tags": json.dumps(["热学", "热传导"])
    },
    {
        "formula_id": "phy_thermal_expansion",
        "name": "热膨胀公式",
        "subject": "physics",
        "category": "physics_thermodynamics",
        "subcategory": "expansion",
        "formula_latex": "\\Delta L = \\alpha L_0 \\Delta T",
        "formula_plain": "ΔL = αL₀ΔT",
        "description": "线膨胀公式",
        "variables": json.dumps({"ΔL": "长度变化", "α": "线膨胀系数", "L₀": "原长", "ΔT": "温度变化"}),
        "units": json.dumps({"L": "m", "α": "K⁻¹", "T": "K"}),
        "applications": "热膨胀问题",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 0,
        "tags": json.dumps(["热学", "膨胀"])
    },
    {
        "formula_id": "phy_entropy",
        "name": "熵变公式",
        "subject": "physics",
        "category": "physics_thermodynamics",
        "subcategory": "entropy",
        "formula_latex": "\\Delta S = \\frac{Q}{T}",
        "formula_plain": "ΔS = Q/T",
        "description": "等温过程熵变",
        "variables": json.dumps({"ΔS": "熵变", "Q": "热量", "T": "温度"}),
        "units": json.dumps({"S": "J/K", "Q": "J", "T": "K"}),
        "applications": "热力学第二定律",
        "grade_level": "高中",
        "difficulty": 4,
        "is_important": 0,
        "tags": json.dumps(["热学", "熵"])
    },
    
    # ==================== 物理 - 光学 ====================
    {
        "formula_id": "phy_snell",
        "name": "斯涅尔定律",
        "subject": "physics",
        "category": "physics_optics",
        "subcategory": "refraction",
        "formula_latex": "n_1 \\sin\\theta_1 = n_2 \\sin\\theta_2",
        "formula_plain": "n₁sinθ₁ = n₂sinθ₂",
        "description": "光的折射定律",
        "variables": json.dumps({"n₁,n₂": "折射率", "θ₁": "入射角", "θ₂": "折射角"}),
        "units": json.dumps({}),
        "applications": "光学折射问题",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["光学", "折射"])
    },
    {
        "formula_id": "phy_lens",
        "name": "透镜公式",
        "subject": "physics",
        "category": "physics_optics",
        "subcategory": "lenses",
        "formula_latex": "\\frac{1}{f} = \\frac{1}{u} + \\frac{1}{v}",
        "formula_plain": "1/f = 1/u + 1/v",
        "description": "薄透镜成像公式",
        "variables": json.dumps({"f": "焦距", "u": "物距", "v": "像距"}),
        "units": json.dumps({"f,u,v": "m"}),
        "applications": "透镜成像问题",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["光学", "透镜"])
    },
    
    # ==================== 物理 - 波动 ====================
    {
        "formula_id": "phy_wave_speed",
        "name": "波速公式",
        "subject": "physics",
        "category": "physics_waves",
        "subcategory": "wave_properties",
        "formula_latex": "v = f\\lambda",
        "formula_plain": "v = fλ",
        "description": "波速等于频率乘波长",
        "variables": json.dumps({"v": "波速", "f": "频率", "λ": "波长"}),
        "units": json.dumps({"v": "m/s", "f": "Hz", "λ": "m"}),
        "applications": "波动问题",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["波动", "波速"])
    },
    {
        "formula_id": "phy_doppler",
        "name": "多普勒效应公式",
        "subject": "physics",
        "category": "physics_waves",
        "subcategory": "doppler",
        "formula_latex": "f' = f \\frac{v + v_o}{v - v_s}",
        "formula_plain": "f' = f(v + v₀)/(v - vₛ)",
        "description": "多普勒效应频率变化",
        "variables": json.dumps({"f'": "观测频率", "f": "源频率", "v": "波速", "v₀": "观察者速度", "vₛ": "源速度"}),
        "units": json.dumps({"f,f'": "Hz", "v,v₀,vₛ": "m/s"}),
        "applications": "多普勒效应",
        "grade_level": "高中",
        "difficulty": 4,
        "is_important": 0,
        "tags": json.dumps(["波动", "多普勒"])
    },
    
    # ==================== 物理 - 近代物理 ====================
    {
        "formula_id": "phy_einstein",
        "name": "质能方程",
        "subject": "physics",
        "category": "physics_modern",
        "subcategory": "relativity",
        "formula_latex": "E = mc^2",
        "formula_plain": "E = mc²",
        "description": "质量与能量的等价关系",
        "variables": json.dumps({"E": "能量", "m": "质量", "c": "光速3×10⁸m/s"}),
        "units": json.dumps({"E": "J", "m": "kg", "c": "m/s"}),
        "applications": "核能计算",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["近代物理", "相对论"])
    },
    {
        "formula_id": "phy_planck",
        "name": "普朗克公式",
        "subject": "physics",
        "category": "physics_modern",
        "subcategory": "quantum",
        "formula_latex": "E = h\\nu",
        "formula_plain": "E = hν",
        "description": "光子能量",
        "variables": json.dumps({"E": "能量", "h": "普朗克常量6.63×10⁻³⁴", "ν": "频率"}),
        "units": json.dumps({"E": "J", "h": "J·s", "ν": "Hz"}),
        "applications": "量子物理",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["近代物理", "量子"])
    },
    
    # ==================== 化学 - 无机化学 ====================
    {
        "formula_id": "chem_mole",
        "name": "物质的量公式",
        "subject": "chemistry",
        "category": "chemistry_inorganic",
        "subcategory": "mole_concept",
        "formula_latex": "n = \\frac{m}{M}",
        "formula_plain": "n = m/M",
        "description": "物质的量等于质量除以摩尔质量",
        "variables": json.dumps({"n": "物质的量", "m": "质量", "M": "摩尔质量"}),
        "units": json.dumps({"n": "mol", "m": "g", "M": "g/mol"}),
        "applications": "化学计算",
        "grade_level": "高中",
        "difficulty": 1,
        "is_important": 1,
        "tags": json.dumps(["化学", "摩尔"])
    },
    {
        "formula_id": "chem_avogadro",
        "name": "阿伏伽德罗定律",
        "subject": "chemistry",
        "category": "chemistry_inorganic",
        "subcategory": "gas_laws",
        "formula_latex": "V = n \\cdot V_m",
        "formula_plain": "V = n·Vₘ",
        "description": "气体体积与物质的量成正比",
        "variables": json.dumps({"V": "体积", "n": "物质的量", "Vₘ": "气体摩尔体积22.4L/mol"}),
        "units": json.dumps({"V": "L", "n": "mol", "Vₘ": "L/mol"}),
        "applications": "气体计算",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["化学", "气体定律"])
    },
    {
        "formula_id": "chem_concentration",
        "name": "物质的量浓度",
        "subject": "chemistry",
        "category": "chemistry_inorganic",
        "subcategory": "solutions",
        "formula_latex": "c = \\frac{n}{V}",
        "formula_plain": "c = n/V",
        "description": "物质的量浓度",
        "variables": json.dumps({"c": "浓度", "n": "物质的量", "V": "体积"}),
        "units": json.dumps({"c": "mol/L", "n": "mol", "V": "L"}),
        "applications": "溶液计算",
        "grade_level": "高中",
        "difficulty": 1,
        "is_important": 1,
        "tags": json.dumps(["化学", "溶液"])
    },
    {
        "formula_id": "chem_ph",
        "name": "pH计算公式",
        "subject": "chemistry",
        "category": "chemistry_inorganic",
        "subcategory": "acids_bases",
        "formula_latex": "pH = -\\log[H^+]",
        "formula_plain": "pH = -log[H⁺]",
        "description": "溶液酸碱度计算",
        "variables": json.dumps({"pH": "酸碱度", "[H⁺]": "氢离子浓度"}),
        "units": json.dumps({"[H⁺]": "mol/L"}),
        "applications": "酸碱计算",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["化学", "酸碱"])
    },
    {
        "formula_id": "chem_ksp",
        "name": "溶度积常数",
        "subject": "chemistry",
        "category": "chemistry_inorganic",
        "subcategory": "solubility",
        "formula_latex": "K_{sp} = [M^{n+}]^m [A^{m-}]^n",
        "formula_plain": "K_sp = [Mⁿ⁺]^m [Aᵐ⁻]^n",
        "description": "难溶电解质溶度积",
        "variables": json.dumps({"K_sp": "溶度积常数", "[Mⁿ⁺]": "阳离子浓度", "[Aᵐ⁻]": "阴离子浓度"}),
        "units": json.dumps({"K_sp": "mol^(m+n)/L^(m+n)"}),
        "applications": "溶解度计算",
        "grade_level": "高中",
        "difficulty": 4,
        "is_important": 1,
        "tags": json.dumps(["化学", "溶度积"])
    },
    
    # ==================== 化学 - 有机化学 ====================
    {
        "formula_id": "chem_alkane",
        "name": "烷烃通式",
        "subject": "chemistry",
        "category": "chemistry_organic",
        "subcategory": "hydrocarbons",
        "formula_latex": "C_n H_{2n+2}",
        "formula_plain": "CₙH₂ₙ₊₂",
        "description": "烷烃的分子通式",
        "variables": json.dumps({"n": "碳原子数"}),
        "units": json.dumps({}),
        "applications": "有机物分子式",
        "grade_level": "高中",
        "difficulty": 1,
        "is_important": 1,
        "tags": json.dumps(["化学", "有机物"])
    },
    {
        "formula_id": "chem_alkene",
        "name": "烯烃通式",
        "subject": "chemistry",
        "category": "chemistry_organic",
        "subcategory": "hydrocarbons",
        "formula_latex": "C_n H_{2n}",
        "formula_plain": "CₙH₂ₙ",
        "description": "烯烃的分子通式",
        "variables": json.dumps({"n": "碳原子数"}),
        "units": json.dumps({}),
        "applications": "有机物分子式",
        "grade_level": "高中",
        "difficulty": 1,
        "is_important": 1,
        "tags": json.dumps(["化学", "有机物"])
    },
    {
        "formula_id": "chem_alkyne",
        "name": "炔烃通式",
        "subject": "chemistry",
        "category": "chemistry_organic",
        "subcategory": "hydrocarbons",
        "formula_latex": "C_n H_{2n-2}",
        "formula_plain": "CₙH₂ₙ₋₂",
        "description": "炔烃的分子通式",
        "variables": json.dumps({"n": "碳原子数"}),
        "units": json.dumps({}),
        "applications": "有机物分子式",
        "grade_level": "高中",
        "difficulty": 1,
        "is_important": 1,
        "tags": json.dumps(["化学", "有机物"])
    },
    
    # ==================== 化学 - 物理化学 ====================
    {
        "formula_id": "chem_ideal_gas",
        "name": "理想气体状态方程",
        "subject": "chemistry",
        "category": "chemistry_physical",
        "subcategory": "thermodynamics",
        "formula_latex": "PV = nRT",
        "formula_plain": "PV = nRT",
        "description": "理想气体压强、体积、温度关系",
        "variables": json.dumps({"P": "压强", "V": "体积", "n": "物质的量", "R": "气体常量", "T": "温度"}),
        "units": json.dumps({"P": "Pa", "V": "m³", "n": "mol", "T": "K"}),
        "applications": "气体问题",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["化学", "物理化学"])
    },
    {
        "formula_id": "chem_hess",
        "name": "盖斯定律",
        "subject": "chemistry",
        "category": "chemistry_physical",
        "subcategory": "enthalpy",
        "formula_latex": "\\Delta H = \\sum \\Delta H_{products} - \\sum \\Delta H_{reactants}",
        "formula_plain": "ΔH = ΣΔH(产物) - ΣΔH(反应物)",
        "description": "化学反应焓变计算",
        "variables": json.dumps({"ΔH": "焓变", "ΔH(产物)": "产物标准生成焓", "ΔH(反应物)": "反应物标准生成焓"}),
        "units": json.dumps({"ΔH": "kJ/mol"}),
        "applications": "热化学计算",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["化学", "热化学"])
    },
    {
        "formula_id": "chem_rate",
        "name": "反应速率公式",
        "subject": "chemistry",
        "category": "chemistry_physical",
        "subcategory": "kinetics",
        "formula_latex": "v = k[A]^m [B]^n",
        "formula_plain": "v = k[A]^m[B]^n",
        "description": "化学反应速率方程",
        "variables": json.dumps({"v": "反应速率", "k": "速率常数", "[A],[B]": "反应物浓度", "m,n": "反应级数"}),
        "units": json.dumps({"v": "mol/(L·s)", "[A],[B]": "mol/L"}),
        "applications": "反应动力学",
        "grade_level": "高中",
        "difficulty": 4,
        "is_important": 1,
        "tags": json.dumps(["化学", "反应速率"])
    },
    {
        "formula_id": "chem_equilibrium",
        "name": "化学平衡常数",
        "subject": "chemistry",
        "category": "chemistry_physical",
        "subcategory": "equilibrium",
        "formula_latex": "K = \\frac{[C]^c [D]^d}{[A]^a [B]^b}",
        "formula_plain": "K = [C]^c[D]^d/([A]^a[B]^b)",
        "description": "化学平衡常数表达式",
        "variables": json.dumps({"K": "平衡常数", "[A],[B],[C],[D]": "各物质浓度", "a,b,c,d": "化学计量数"}),
        "units": json.dumps({}),
        "applications": "化学平衡",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["化学", "化学平衡"])
    },
    
    # ==================== 化学 - 分析化学 ====================
    {
        "formula_id": "chem_titration",
        "name": "滴定公式",
        "subject": "chemistry",
        "category": "chemistry_analytical",
        "subcategory": "titration",
        "formula_latex": "c_1 V_1 = c_2 V_2",
        "formula_plain": "c₁V₁ = c₂V₂",
        "description": "酸碱滴定基本公式",
        "variables": json.dumps({"c₁": "标准溶液浓度", "V₁": "标准溶液体积", "c₂": "待测溶液浓度", "V₂": "待测溶液体积"}),
        "units": json.dumps({"c": "mol/L", "V": "L"}),
        "applications": "滴定分析",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["化学", "滴定"])
    },
    
    # ==================== 生物 - 细胞生物学 ====================
    {
        "formula_id": "bio_cell_respiration",
        "name": "细胞呼吸方程式",
        "subject": "biology",
        "category": "biology_cell",
        "subcategory": "respiration",
        "formula_latex": "C_6 H_{12} O_6 + 6O_2 \\rightarrow 6CO_2 + 6H_2 O + ATP",
        "formula_plain": "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP",
        "description": "有氧呼吸总方程式",
        "variables": json.dumps({"C₆H₁₂O₆": "葡萄糖", "O₂": "氧气", "CO₂": "二氧化碳", "H₂O": "水", "ATP": "能量"}),
        "units": json.dumps({}),
        "applications": "细胞代谢",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["生物", "细胞呼吸"])
    },
    {
        "formula_id": "bio_photosynthesis",
        "name": "光合作用方程式",
        "subject": "biology",
        "category": "biology_cell",
        "subcategory": "photosynthesis",
        "formula_latex": "6CO_2 + 6H_2 O + 光能 \\rightarrow C_6 H_{12} O_6 + 6O_2",
        "formula_plain": "6CO₂ + 6H₂O + 光能 → C₆H₁₂O₆ + 6O₂",
        "description": "光合作用总方程式",
        "variables": json.dumps({"CO₂": "二氧化碳", "H₂O": "水", "光能": "光能量", "C₆H₁₂O₆": "葡萄糖", "O₂": "氧气"}),
        "units": json.dumps({}),
        "applications": "植物代谢",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["生物", "光合作用"])
    },
    
    # ==================== 生物 - 遗传学 ====================
    {
        "formula_id": "bio_genetic_prob",
        "name": "遗传概率公式",
        "subject": "biology",
        "category": "biology_genetics",
        "subcategory": "probability",
        "formula_latex": "P(A \\cap B) = P(A) \\times P(B)",
        "formula_plain": "P(A∩B) = P(A)×P(B)",
        "description": "独立遗传事件概率",
        "variables": json.dumps({"P(A∩B)": "联合概率", "P(A)": "事件A概率", "P(B)": "事件B概率"}),
        "units": json.dumps({}),
        "applications": "遗传计算",
        "grade_level": "高中",
        "difficulty": 3,
        "is_important": 1,
        "tags": json.dumps(["生物", "遗传学"])
    },
    
    # ==================== 生物 - 分子生物学 ====================
    {
        "formula_id": "bio_dna_base",
        "name": "DNA碱基配对规律",
        "subject": "biology",
        "category": "biology_molecular",
        "subcategory": "dna_structure",
        "formula_latex": "A=T, \\quad G=C",
        "formula_plain": "A=T, G=C",
        "description": "DNA中碱基互补配对原则",
        "variables": json.dumps({"A": "腺嘌呤", "T": "胸腺嘧啶", "G": "鸟嘌呤", "C": "胞嘧啶"}),
        "units": json.dumps({}),
        "applications": "DNA结构",
        "grade_level": "高中",
        "difficulty": 2,
        "is_important": 1,
        "tags": json.dumps(["生物", "DNA"])
    },
]


def import_formulas(db: EnhancedDatabaseManager):
    """导入理科公式数据"""
    print("\n📚 开始导入理科公式数据...")
    
    current_time = int(time.time())
    
    # 导入公式分类
    print("\n  📁 导入公式分类...")
    for category in FORMULA_CATEGORIES:
        category_data = category.copy()
        category_data['created_at'] = current_time
        try:
            db.add('formula_categories', category_data)
            print(f"    ✅ 创建分类: {category['name']}")
        except Exception as e:
            print(f"    ⏭️ 分类已存在: {category['name']}")
    
    # 导入公式数据
    print("\n  📖 导入公式数据...")
    count = 0
    for formula in SCIENCE_FORMULAS:
        formula_data = formula.copy()
        formula_data['created_at'] = current_time
        formula_data['updated_at'] = current_time
        try:
            db.add('science_formulas', formula_data)
            count += 1
            if count % 20 == 0:
                print(f"    已导入 {count} 条公式...")
        except Exception as e:
            print(f"    ⏭️ 跳过重复公式: {formula['name']}")
    
    print(f"  ✅ 共导入 {count} 条公式")
    print("\n✅ 理科公式数据导入完成")


def main():
    """主函数"""
    print("""
╔══════════════════════════════════════════════════════════╗
║           理科公式数据导入工具                             ║
╚══════════════════════════════════════════════════════════╝
    """)
    
    db_path = "data/mtscos_new.db"
    script_dir = os.path.dirname(os.path.abspath(__file__))
    full_path = os.path.join(script_dir, '..', db_path)
    
    print(f"📦 数据库路径: {db_path}")
    
    db = EnhancedDatabaseManager(full_path, SCHEMA)
    
    import_formulas(db)
    
    print("\n📊 导入后统计:")
    stats = db.get_stats()
    print(f"  公式分类数: {stats.get('formula_categories', 0)}")
    print(f"  公式数量: {stats.get('science_formulas', 0)}")
    
    db.close()
    
    print("""
╔══════════════════════════════════════════════════════════╗
║                   导入完成！                              ║
╚══════════════════════════════════════════════════════════╝
    """)


if __name__ == '__main__':
    main()