"""
文科知识数据
包含：古诗词、文言文、课文选段、成语、歇后语、文学选段、阅读理解、经典语录
"""

POEMS = [
    {"title": "静夜思", "author": "李白", "dynasty": "唐",
     "content": "床前明月光，疑是地上霜。\n举头望明月，低头思故乡。",
     "pinyin": "chuang qian ming yue guang, yi shi di shang shuang.\nju tou wang ming yue, di tou si gu xiang.",
     "translation": "明亮的月光洒在床前的窗户纸上，好像地上泛起了一层白霜。\n我禁不住抬起头来，看那天窗外空中的一轮明月，不由得低头沉思，想起远方的家乡。",
     "annotation": "床：此处指井栏。疑：好像。举头：抬头。",
     "genre": "诗", "theme": "思乡", "grade_level": "1-3",
     "requirement": "recite", "difficulty": 1, "is_classic": 1,
     "tags": ["思乡", "月亮", "唐诗"]},
    {"title": "春晓", "author": "孟浩然", "dynasty": "唐",
     "content": "春眠不觉晓，处处闻啼鸟。\n夜来风雨声，花落知多少。",
     "pinyin": "chun mian bu jue xiao, chu chu wen ti niao.\nye lai feng yu sheng, hua luo zhi duo shao.",
     "translation": "春日里贪睡不知不觉天已破晓，到处可以听见小鸟的鸣叫声。\n回想昨夜的阵阵风雨声，不知道吹落了多少娇美的春花。",
     "annotation": "晓：天亮。闻：听见。啼鸟：鸟的啼叫声。",
     "genre": "诗", "theme": "山水", "grade_level": "1-3",
     "requirement": "recite", "difficulty": 1, "is_classic": 1,
     "tags": ["春天", "自然", "唐诗"]},
    {"title": "登鹳雀楼", "author": "王之涣", "dynasty": "唐",
     "content": "白日依山尽，黄河入海流。\n欲穷千里目，更上一层楼。",
     "pinyin": "bai ri yi shan jin, huang he ru hai liu.\nyu qiong qian li mu, geng shang yi ceng lou.",
     "translation": "夕阳依傍着山峦渐渐下落，滔滔黄河朝着大海汹涌奔流。\n若想把千里的风光景物看够，那就要登上更高的一层城楼。",
     "annotation": "鹳雀楼：古楼名，在今山西永济市。尽：消失。穷：尽，使达到极点。",
     "genre": "诗", "theme": "哲理", "grade_level": "1-3",
     "requirement": "recite", "difficulty": 1, "is_classic": 1,
     "tags": ["哲理", "登高", "唐诗"]},
    {"title": "望庐山瀑布", "author": "李白", "dynasty": "唐",
     "content": "日照香炉生紫烟，遥看瀑布挂前川。\n飞流直下三千尺，疑是银河落九天。",
     "pinyin": "ri zhao xiang lu sheng zi yan, yao kan pu bu gua qian chuan.\nfei liu zhi xia san qian chi, yi shi yin he luo jiu tian.",
     "translation": "香炉峰在阳光的照射下生起紫色烟霞，从远处看去瀑布好似白色绢绸悬挂山前。\n高崖上飞腾直落的瀑布好像有几千尺，令人怀疑是银河从天上倾泻落到人间。",
     "annotation": "香炉：指香炉峰。紫烟：指日光透过云雾，远望如紫色的烟云。川：河流，这里指瀑布。九天：天的最高处，形容极高。",
     "genre": "诗", "theme": "山水", "grade_level": "3-6",
     "requirement": "recite", "difficulty": 2, "is_classic": 1,
     "tags": ["山水", "瀑布", "唐诗"]},
    {"title": "江雪", "author": "柳宗元", "dynasty": "唐",
     "content": "千山鸟飞绝，万径人踪灭。\n孤舟蓑笠翁，独钓寒江雪。",
     "pinyin": "qian shan niao fei jue, wan jing ren zong mie.\ngu zhou suo li weng, du diao han jiang xue.",
     "translation": "所有的山上飞鸟的身影已经绝迹，所有道路都不见人的踪迹。\n江面孤舟上一个披簑戴笠的渔翁，独自在大雪覆盖的寒冷江面上垂钓。",
     "annotation": "绝：无，没有。万径：虚指，指千万条路。人踪：人的脚印。孤：孤零零。蓑笠：蓑衣和斗笠。",
     "genre": "诗", "theme": "山水", "grade_level": "3-6",
     "requirement": "recite", "difficulty": 2, "is_classic": 1,
     "tags": ["冬天", "山水", "唐诗"]},
    {"title": "咏鹅", "author": "骆宾王", "dynasty": "唐",
     "content": "鹅，鹅，鹅，曲项向天歌。\n白毛浮绿水，红掌拨清波。",
     "pinyin": "e, e, e, qu xiang xiang tian ge.\nbai mao fu lv shui, hong zhang bo qing bo.",
     "translation": "鹅呀，鹅呀，曲着脖子向天欢叫。\n洁白的羽毛漂浮在碧绿水面上，红红的脚掌拨动着清清水波。",
     "annotation": "曲项：弯曲的脖子。歌：长鸣。浮：漂浮。拨：划动。",
     "genre": "诗", "theme": "动物", "grade_level": "1-3",
     "requirement": "recite", "difficulty": 1, "is_classic": 1,
     "tags": ["动物", "儿童诗", "唐诗"]},
    {"title": "悯农", "author": "李绅", "dynasty": "唐",
     "content": "锄禾日当午，汗滴禾下土。\n谁知盘中餐，粒粒皆辛苦。",
     "pinyin": "chu he ri dang wu, han di he xia tu.\nshei zhi pan zhong can, li li jie xin ku.",
     "translation": "盛夏中午，烈日炎炎，农民还在劳作，汗珠滴入泥土。\n有谁想到，我们碗中的米饭，粒粒饱含着农民的血汗？",
     "annotation": "禾：谷类植物的统称。餐：一作\"飧\"，熟食的通称。",
     "genre": "诗", "theme": "民生", "grade_level": "1-3",
     "requirement": "recite", "difficulty": 1, "is_classic": 1,
     "tags": ["农民", "劳动", "唐诗"]},
    {"title": "枫桥夜泊", "author": "张继", "dynasty": "唐",
     "content": "月落乌啼霜满天，江枫渔火对愁眠。\n姑苏城外寒山寺，夜半钟声到客船。",
     "pinyin": "yue luo wu ti shuang man tian, jiang feng yu huo dui chou mian.\ngu su cheng wai han shan si, ye ban zhong sheng dao ke chuan.",
     "translation": "月亮已落下乌鸦啼叫寒气满天，江边枫树与船上渔火，难抵我独自傍愁而眠。\n姑苏城外那寂寞清静寒山古寺，半夜里敲钟的声音传到了客船。",
     "annotation": "枫桥：在今苏州市阊门外。夜泊：夜间把船停靠在岸边。乌啼：一说为乌鸦啼鸣，一说为乌啼镇。姑苏：苏州的别称。寒山寺：在枫桥附近。",
     "genre": "诗", "theme": "思乡", "grade_level": "6-9",
     "requirement": "recite", "difficulty": 3, "is_classic": 1,
     "tags": ["思乡", "夜景", "唐诗"]},
    {"title": "出塞", "author": "王昌龄", "dynasty": "唐",
     "content": "秦时明月汉时关，万里长征人未还。\n但使龙城飞将在，不教胡马度阴山。",
     "pinyin": "qin shi ming yue han shi guan, wan li chang zheng ren wei huan.\ndan shi long cheng fei jiang zai, bu jiao hu ma du yin shan.",
     "translation": "依旧是秦汉时期的明月和边关，守边御敌鏖战万里征人未回还。\n倘若龙城的飞将李广如今还在，绝不许匈奴南下牧马度过阴山。",
     "annotation": "但使：只要。龙城飞将：指汉朝名将李广。胡马：指侵扰内地的外族骑兵。度：越过。阴山：昆仑山的北支，起自河套西北，横贯绥远、察哈尔及热河北部，是中国北方的屏障。",
     "genre": "诗", "theme": "边塞", "grade_level": "6-9",
     "requirement": "recite", "difficulty": 3, "is_classic": 1,
     "tags": ["边塞", "爱国", "唐诗"]},
    {"title": "示儿", "author": "陆游", "dynasty": "宋",
     "content": "死去元知万事空，但悲不见九州同。\n王师北定中原日，家祭无忘告乃翁。",
     "pinyin": "si qu yuan zhi wan shi kong, dan bei bu jian jiu zhou tong.\nwang shi bei ding zhong yuan ri, jia ji wu wang gao nai weng.",
     "translation": "我本来就知道，当我死后，人间的一切就都和我无关了；但唯一使我痛心的，就是我没能亲眼看到祖国的统一。\n因此，当大宋军队收复了中原失地的那一天到来之时，你们举行家祭，千万别忘把这好消息告诉你们的父亲！",
     "annotation": "示儿：写给儿子们看。元知：原本知道。九州：指中国。同：统一。王师：指朝廷的军队。北定：将北方平定。中原：指淮河以北被金人侵占的地区。家祭：祭祀祖先。乃翁：你的父亲。",
     "genre": "诗", "theme": "爱国", "grade_level": "6-9",
     "requirement": "recite", "difficulty": 3, "is_classic": 1,
     "tags": ["爱国", "遗言", "宋诗"]},
    {"title": "水调歌头·明月几时有", "author": "苏轼", "dynasty": "宋",
     "content": "明月几时有？把酒问青天。不知天上宫阙，今夕是何年。\n我欲乘风归去，又恐琼楼玉宇，高处不胜寒。\n起舞弄清影，何似在人间。\n\n转朱阁，低绮户，照无眠。不应有恨，何事长向别时圆？\n人有悲欢离合，月有阴晴圆缺，此事古难全。\n但愿人长久，千里共婵娟。",
     "pinyin": "ming yue ji shi you? ba jiu wen qing tian. bu zhi tian shang gong que, jin xi shi he nian.\nwo yu cheng feng gui qu, you kong qiong lou yu yu, gao chu bu sheng han.\nqi wu nong qing ying, he si zai ren jian.\n\nzhuan zhu ge, di qi hu, zhao wu mian. bu ying you hen, he shi chang xiang bie shi yuan?\nren you bei huan li he, yue you yin qing yuan que, ci shi gu nan quan.\ndan yuan ren chang jiu, qian li gong chan juan.",
     "translation": "明月从什么时候才开始出现的？我端起酒杯遥问苍天。不知道在天上的宫殿，何年何月。\n我想要乘御清风回到天上，又恐怕在美玉砌成的楼宇，受不住高耸九天的寒冷。\n翩翩起舞玩赏着月下清影，哪像是在人间。\n\n转过朱红楼阁，月光低洒在雕花的窗户上，照着没有睡意的自己。明月不该对人们有什么怨恨吧，为什么偏在人们离别时才圆呢？\n人有悲欢离合的变迁，月有阴晴圆缺的转换，这种事自古来难以周全。\n只希望这世上所有人的亲人能平安健康，即便相隔千里，也能共享这美好的月光。",
     "annotation": "水调歌头：词牌名。宫阙：宫殿。琼楼玉宇：美玉砌成的楼宇，指想象中的仙宫。不胜：经受不住。弄清影：月光下的身影也跟着做出各种舞姿。婵娟：指月亮。",
     "genre": "词", "theme": "思念", "grade_level": "9",
     "requirement": "recite", "difficulty": 4, "is_classic": 1,
     "tags": ["思念", "中秋", "宋词"]},
    {"title": "虞美人·春花秋月何时了", "author": "李煜", "dynasty": "南唐",
     "content": "春花秋月何时了？往事知多少。\n小楼昨夜又东风，故国不堪回首月明中。\n\n雕栏玉砌应犹在，只是朱颜改。\n问君能有几多愁？恰似一江春水向东流。",
     "pinyin": "chun hua qiu yue he shi liao? wang shi zhi duo shao.\nxiao lou zuo ye you dong feng, gu guo bu kan hui shou yue ming zhong.\n\ndiao lan yu qi ying you zai, zhi shi zhu yan gai.\nwen jun neng you ji duo chou? qia si yi jiang chun shui xiang dong liu.",
     "translation": "这年的时光什么时候才能结束，往事知道有多少！\n昨夜小楼上又吹来了春风，在这皓月当空的夜晚怎能忍受得了回忆故国的伤痛。\n\n精雕细刻的栏杆、玉石砌成的台阶应该都还在，只是所怀念的人已经衰老。\n问你心中有多少哀愁，就像那不尽的春江之水滚滚向东流。",
     "annotation": "虞美人：词牌名。了：了结，完结。砌：台阶。雕栏玉砌：指远在金陵的南唐故宫。朱颜改：指所怀念的人已衰老。君：作者自称。能：或作\"都\"\"那\"\"还\"。",
     "genre": "词", "theme": "亡国", "grade_level": "9",
     "requirement": "understand", "difficulty": 4, "is_classic": 1,
     "tags": ["亡国", "愁思", "宋词"]}
]


CLASSICAL_CHINESE = [
    {"title": "论语·学而", "author": "孔子及其弟子", "dynasty": "春秋",
     "original_text": "子曰：\"学而时习之，不亦说乎？有朋自远方来，不亦乐乎？人不知而不愠，不亦君子乎？\"",
     "modern_translation": "孔子说：\"学习并且按时地去复习，不也很快乐吗？有志同道合的人从远方来，不也很高兴吗？别人不了解我但我不生气，不也是道德上有修养的人吗？\"",
     "word_notes": {"子": "先生，指孔子。", "曰": "说。", "学": "学习。", "时习": "按时复习。",
                    "说": "通\"悦\"，愉快。", "朋": "志同道合的人。", "愠": "生气，发怒。",
                    "君子": "这里指道德上有修养的人。"},
     "sentence_analysis": ["学而时习之，不亦说乎？——学习并按时复习，这是一件快乐的事。",
                          "有朋自远方来，不亦乐乎？——有志同道合的朋友从远方来访，这是一件令人高兴的事。",
                          "人不知而不愠，不亦君子乎？——别人不了解自己而不生气，这才是君子的风范。"],
     "grammar_points": ["反问句", "通假字"],
     "cultural_context": "《论语》是儒家学派的经典著作之一，由孔子的弟子及其再传弟子编撰而成。它以语录体和对话文体为主，记录了孔子及其弟子言行，集中体现了孔子的政治主张、伦理思想、道德观念及教育原则等。",
     "grade_level": "6-9", "requirement": "recite", "difficulty": 3, "is_classic": 1,
     "tags": ["论语", "学习", "儒家"]},
    {"title": "桃花源记", "author": "陶渊明", "dynasty": "东晋",
     "original_text": "晋太元中，武陵人捕鱼为业。缘溪行，忘路之远近。忽逢桃花林，夹岸数百步，中无杂树，芳草鲜美，落英缤纷。渔人甚异之。复前行，欲穷其林。",
     "modern_translation": "东晋太元年间，武陵郡有个人以打鱼为生。一天他顺着溪水划船，忘记了路程的远近。忽然遇到一片桃花林，生长在溪水的两岸，长达几百步，中间没有别的树，花草鲜嫩美丽，落花纷纷的散在地上。渔人对此感到十分诧异。继续往前走，想走到林子的尽头。",
     "word_notes": {"太元": "东晋孝武帝的年号。", "武陵": "郡名，现在湖南常德一带。",
                    "缘": "沿着，顺着。", "行": "前行，走。", "远近": "偏义复词，这里指远。",
                    "逢": "遇到。", "夹岸": "两岸。", "杂": "别的，其他的。",
                    "鲜美": "鲜艳美丽。", "落英": "落花。", "缤纷": "繁多而纷乱的样子。",
                    "异": "形容词的意动用法，对……感到诧异。", "复": "又，再。",
                    "穷": "尽，形容词用做动词，走到……的尽头。"},
     "sentence_analysis": ["缘溪行，忘路之远近。——沿着溪水划船，忘记了路程的远近。",
                          "忽逢桃花林，夹岸数百步，中无杂树，芳草鲜美，落英缤纷。——忽然遇到一片桃花林，两岸几百步内，中间没有别的树木，花草鲜艳美丽，落花缤纷。",
                          "渔人甚异之。复前行，欲穷其林。——渔人对此感到非常惊讶。继续往前走，想要走到林子的尽头。"],
     "grammar_points": ["意动用法", "偏义复词", "形容词动用"],
     "cultural_context": "《桃花源记》是东晋文学家陶渊明的代表作之一，是《桃花源诗》的序言，选自《陶渊明集》。此文借武陵渔人行踪这一线索，把现实和理想境界联系起来，通过对桃花源的安宁和乐、自由平等生活的描绘，表现了作者追求美好生活的理想和对现实生活的不满。",
     "grade_level": "9", "requirement": "understand", "difficulty": 4, "is_classic": 1,
     "tags": ["桃花源", "陶渊明", "东晋"]},
    {"title": "陋室铭", "author": "刘禹锡", "dynasty": "唐",
     "original_text": "山不在高，有仙则名。水不在深，有龙则灵。斯是陋室，惟吾德馨。苔痕上阶绿，草色入帘青。谈笑有鸿儒，往来无白丁。可以调素琴，阅金经。无丝竹之乱耳，无案牍之劳形。南阳诸葛庐，西蜀子云亭。孔子云：何陋之有？",
     "modern_translation": "山不在于高，有了神仙就出名。水不在于深，有了龙就显得有了灵气。这是简陋的房子，只是我（住屋的人）品德好（就感觉不到简陋了）。长到台阶上的苔痕颜色碧绿；草色青葱，映入帘中。到这里谈笑的都是知识渊博的大学者，交往的没有知识浅薄的人。可以弹奏不加装饰的古琴，阅读佛经。没有奏乐的声音扰乱双耳，没有官府的公文使身体劳累。南阳有诸葛亮的草庐，西蜀有扬子云的亭子。孔子说：有什么简陋的呢？",
     "word_notes": {"陋室": "简陋的屋子。", "铭": "古代刻在器物上用来警戒自己或称述功德的文字，后来成为一种文体。",
                    "名": "出名，著名。", "灵": "神奇灵异。", "斯": "这。", "惟": "只。",
                    "吾": "我。", "德馨": "品德高尚。馨，能散布很远的香气，这里指德行美好。",
                    "鸿儒": "博学的人。鸿，大。儒，旧指读书人。",
                    "白丁": "平民，这里指没有什么学问的人。",
                    "调素琴": "弹奏不加装饰的古琴。调，调弄，这里指弹（琴）。素琴，不加装饰的琴。",
                    "金经": "指佛经。",
                    "丝竹": "琴瑟、箫管等乐器的总称，这里指奏乐的声音。",
                    "案牍": "官府的公文，文书。",
                    "劳形": "使身体劳累。劳，形容词的使动用法，使……劳累。形，形体、身体。"},
     "sentence_analysis": ["山不在高，有仙则名。水不在深，有龙则灵。——山不在于高，有了神仙就出名；水不在于深，有了龙就显得有灵气。",
                          "斯是陋室，惟吾德馨。——这是简陋的屋子，只是因为我的品德高尚，就不觉得简陋了。",
                          "苔痕上阶绿，草色入帘青。——苔痕蔓延到台阶上，使台阶都绿了；草色映入眼帘，使室内都青了。",
                          "谈笑有鸿儒，往来无白丁。——到这里谈笑的都是学识渊博的人，来往的没有浅薄之人。",
                          "无丝竹之乱耳，无案牍之劳形。——没有嘈杂的音乐扰乱耳朵，没有官府的公文劳累身心。",
                          "孔子云：何陋之有？——孔子说：有什么简陋的呢？"],
     "grammar_points": ["判断句", "倒装句", "使动用法", "借代"],
     "cultural_context": "《陋室铭》是唐代诗人刘禹锡所创作的一篇托物言志铭文。全文短短八十一字，作者借赞美陋室抒写自己志行高洁，安贫乐道，不与世俗同流合污的人生追求。",
     "grade_level": "7-9", "requirement": "recite", "difficulty": 3, "is_classic": 1,
     "tags": ["陋室铭", "刘禹锡", "托物言志"]},
    {"title": "爱莲说", "author": "周敦颐", "dynasty": "宋",
     "original_text": "水陆草木之花，可爱者甚蕃。晋陶渊明独爱菊。自李唐来，世人甚爱牡丹。予独爱莲之出淤泥而不染，濯清涟而不妖，中通外直，不蔓不枝，香远益清，亭亭净植，可远观而不可亵玩焉。",
     "modern_translation": "水上、陆地上各种草本木本的花，值得喜爱的非常多。晋代的陶渊明唯独喜爱菊花。从李氏唐朝以来，世人大多喜爱牡丹。我唯独喜爱莲花从积存的淤泥中长出却不被污染，经过清水的洗涤却不显得妖艳。（它的茎）中间贯通外形挺直，不生蔓，不长枝，香气传播更加清香，笔直洁净地竖立在水中。（人们）可以远远地观赏（莲），而不可轻易地玩弄它啊。",
     "word_notes": {"说": "一种议论文的文体，可以直接说明事物或论述道理，也可以借人、借事或借物的记载来论述道理。",
                    "蕃": "多。", "独": "只，仅仅。", "予": "我。",
                    "淤泥": "河沟或池塘里积存的污泥。", "染": "沾染（污秽）。",
                    "濯": "洗涤。", "清涟": "水清而有微波，这里指清水。",
                    "妖": "美丽而不端庄。", "中通外直": "（它的茎）中间贯通，外形挺直。",
                    "不蔓不枝": "不生枝蔓，不长枝节。",
                    "香远益清": "香气远播，更加清香。益，更加。",
                    "亭亭净植": "笔直地洁净地立在那里。亭亭，耸立的样子。植，树立。",
                    "亵玩": "靠近玩弄。亵，亲近而不庄重。"},
     "sentence_analysis": ["水陆草木之花，可爱者甚蕃。——水上、陆地上各种花草，值得喜爱的很多。",
                          "予独爱莲之出淤泥而不染，濯清涟而不妖。——我唯独喜爱莲花从淤泥中生长出来却不被污染，经过清水洗涤却不显得妖艳。",
                          "中通外直，不蔓不枝，香远益清，亭亭净植。——（莲的茎）中间贯通，外形挺直，不生枝蔓，不长枝节，香气远播，更加清香，笔直洁净地立在那里。",
                          "可远观而不可亵玩焉。——可以远远观赏，但不能靠近玩弄。"],
     "grammar_points": ["判断句", "省略句", "对比手法"],
     "cultural_context": "《爱莲说》是北宋理学家周敦颐创作的一篇散文。这篇文章通过对莲的形象和品质的描写，歌颂了莲花坚贞的品格，从而也表现了作者洁身自爱的高洁人格和洒落的胸襟。",
     "grade_level": "7-9", "requirement": "recite", "difficulty": 3, "is_classic": 1,
     "tags": ["爱莲说", "周敦颐", "托物言志"]},
    {"title": "岳阳楼记", "author": "范仲淹", "dynasty": "宋",
     "original_text": "庆历四年春，滕子京谪守巴陵郡。越明年，政通人和，百废具兴。乃重修岳阳楼，增其旧制，刻唐贤今人诗赋于其上。属予作文以记之。",
     "modern_translation": "庆历四年的春天，滕子京被降职到巴陵郡做太守。到了第二年，政事顺利，百姓和乐，各种荒废的事业都兴办起来了。于是重新修建岳阳楼，扩大它原有的规模，把唐代名家和当代人的诗赋刻在它上面。嘱托我写一篇文章来记述这件事情。",
     "word_notes": {"庆历四年": "公元1044年。庆历，宋仁宗赵祯的年号。",
                    "滕子京": "名宗谅，字子京，范仲淹的朋友。",
                    "谪守": "因罪贬谪流放，出任外官。",
                    "巴陵郡": "即岳州，治所在今湖南岳阳。",
                    "越明年": "到了第二年。",
                    "政通人和": "政事顺利，百姓和乐。",
                    "百废具兴": "各种荒废的事业都兴办起来了。具，通\"俱\"，全、皆。",
                    "增其旧制": "扩大它原有的规模。增，扩大。制，规模。",
                    "属": "通\"嘱\"，嘱托。", "作文": "写文章。"},
     "sentence_analysis": ["庆历四年春，滕子京谪守巴陵郡。——庆历四年的春天，滕子京被贬为巴陵郡太守。",
                          "越明年，政通人和，百废具兴。——到了第二年，政事顺利，百姓和乐，各种荒废的事业都兴办起来了。",
                          "乃重修岳阳楼，增其旧制，刻唐贤今人诗赋于其上。——于是重新修建岳阳楼，扩大它原有的规模，把唐代和当代名人的诗赋刻在上面。",
                          "属予作文以记之。——嘱托我写一篇文章来记述这件事。"],
     "grammar_points": ["通假字", "省略句"],
     "cultural_context": "《岳阳楼记》是北宋文学家范仲淹于庆历六年九月十五日（1046年10月17日）应好友巴陵郡太守滕子京之请为重修岳阳楼而创作的一篇散文。这篇文章通过写岳阳楼的景色，以及阴雨和晴朗时带给人的不同感受，揭示了\"不以物喜，不以己悲\"的古仁人之心，也表达了自己\"先天下之忧而忧，后天下之乐而乐\"的爱国爱民情怀。",
     "grade_level": "9", "requirement": "understand", "difficulty": 4, "is_classic": 1,
     "tags": ["岳阳楼记", "范仲淹", "忧乐观"]}
]


TEXTBOOK_SEGMENTS = [
    {"title": "从百草园到三味书屋", "author": "鲁迅", "source": "人教版七年级下册",
     "content": "不必说碧绿的菜畦，光滑的石井栏，高大的皂荚树，紫红的桑葚；也不必说鸣蝉在树叶里长吟，肥胖的黄蜂伏在菜花上，轻捷的叫天子（云雀）忽然从草间直窜向云霄里去了。单是周围的短短的泥墙根一带，就有无限趣味。油蛉在这里低唱，蟋蟀们在这里弹琴。翻开断砖来，有时会遇见蜈蚣；还有斑蝥，倘若用手指按住它的脊梁，便会啪的一声，从后窍喷出一阵烟雾。",
     "summary": "这段文字描写了百草园的景色和乐趣，通过对各种动植物的描写，展现了童年生活的美好。",
     "key_points": ["景物描写", "动静结合", "感官描写"],
     "writing_style": "散文",
     "analysis": "作者用\"不必说……也不必说……单是……\"的句式，先写整体的景物，再聚焦局部，层次分明。通过视觉、听觉、触觉、味觉等多种感官描写，使百草园的形象栩栩如生。",
     "subject": "chinese", "grade_level": "7",
     "requirement": "master", "difficulty": 3,
     "tags": ["百草园", "鲁迅", "散文"]},
    {"title": "背影", "author": "朱自清", "source": "人教版八年级上册",
     "content": "我说道：\"爸爸，你走吧。\"他望车外看了看，说：\"我买几个橘子去。你就在此地，不要走动。\"我看那边月台的栅栏外有几个卖东西的等着顾客。走到那边月台，须穿过铁道，须跳下去又爬上去。父亲是一个胖子，走过去自然要费事些。他用两手攀着上面，两脚再向上缩；他肥胖的身子向左微倾，显出努力的样子。",
     "summary": "这段文字描写了父亲送儿子上车时，为儿子买橘子爬月台的情景，展现了父子之间深厚的感情。",
     "key_points": ["细节描写", "动作描写", "情感表达"],
     "writing_style": "散文",
     "analysis": "作者通过细致的动作描写，刻画了父亲爬月台的艰难过程，表达了深沉的父爱。文中对父亲外貌和动作的描写，使父亲的形象生动感人。",
     "subject": "chinese", "grade_level": "8",
     "requirement": "master", "difficulty": 3,
     "tags": ["背影", "朱自清", "父爱"]},
    {"title": "春", "author": "朱自清", "source": "人教版七年级上册",
     "content": "盼望着，盼望着，东风来了，春天的脚步近了。一切都像刚睡醒的样子，欣欣然张开了眼。山朗润起来了，水涨起来了，太阳的脸红起来了。小草偷偷地从土里钻出来，嫩嫩的，绿绿的。园子里，田野里，瞧去，一大片一大片满是的。",
     "summary": "这段文字描绘了春天到来时万物复苏的景象，表现了作者对春天的喜爱和赞美。",
     "key_points": ["拟人手法", "排比修辞", "感官描写"],
     "writing_style": "散文",
     "analysis": "作者运用拟人、排比等修辞手法，从整体到局部，从宏观到微观，描绘了春天的美丽景色。语言生动形象，充满生机。",
     "subject": "chinese", "grade_level": "7",
     "requirement": "master", "difficulty": 2,
     "tags": ["春", "朱自清", "散文"]},
    {"title": "济南的冬天", "author": "老舍", "source": "人教版七年级上册",
     "content": "对于一个在北平住惯的人，像我，冬天要是不刮风，便觉得是奇迹；济南的冬天是没有风声的。对于一个刚由伦敦回来的人，像我，冬天要能看得见日光，便觉得是怪事；济南的冬天是响晴的。自然，在热带的地方，日光是永远那么毒，响亮的天气，反有点叫人害怕。",
     "summary": "这段文字通过对比北平、伦敦和热带的冬天，突出了济南冬天温晴的特点，表达了作者对济南冬天的喜爱。",
     "key_points": ["对比手法", "环境描写", "情感表达"],
     "writing_style": "散文",
     "analysis": "作者运用对比的手法，将济南的冬天与北平、伦敦、热带的冬天进行对比，突出了济南冬天温晴的特点。语言朴实自然，情感真挚。",
     "subject": "chinese", "grade_level": "7",
     "requirement": "master", "difficulty": 2,
     "tags": ["济南的冬天", "老舍", "散文"]},
    {"title": "孔乙己", "author": "鲁迅", "source": "人教版九年级下册",
     "content": "孔乙己是站着喝酒而穿长衫的唯一的人。他身材很高大；青白脸色，皱纹间时常夹些伤痕；一部乱蓬蓬的花白的胡子。穿的虽然是长衫，可是又脏又破，似乎十多年没有补，也没有洗。他对人说话，总是满口之乎者也，教人半懂不懂的。",
     "summary": "这段文字介绍了孔乙己的外貌和身份特点，通过描写他的穿着、神态和语言，刻画了一个迂腐、穷困的知识分子形象。",
     "key_points": ["人物描写", "外貌描写", "语言描写"],
     "writing_style": "小说",
     "analysis": "作者通过外貌描写和语言描写，刻画了孔乙己的形象。\"站着喝酒而穿长衫\"这一细节，揭示了他既放不下读书人的架子，又穷困潦倒的矛盾处境。",
     "subject": "chinese", "grade_level": "9",
     "requirement": "understand", "difficulty": 4,
     "tags": ["孔乙己", "鲁迅", "小说"]}
]


IDIOMS = [
    {"idiom": "一马当先", "pinyin": "yī mǎ dāng xiān",
     "meaning": "作战时策马冲锋在前。形容领先。也比喻工作走在群众前面，积极带头。",
     "story": "出自《三国演义》。三国时期，曹操与马超在潼关交战。曹操的军队被马超打得大败，曹操本人也险些丧命。危急时刻，曹操手下的大将许褚挺身而出，\"一马当先\"，保护曹操突围。",
     "origin": "明·罗贯中《三国演义》第七十一回：\"黄忠一马当先，驰下山来，犹如天崩地塌之势。\"",
     "part_of_speech": "成语",
     "usage": "在这次比赛中，他一马当先，最终获得了第一名。",
     "synonyms": ["遥遥领先", "争先恐后"],
     "antonyms": ["畏缩不前", "甘居人后"],
     "difficulty": 2, "is_common": 1, "grade_level": "3-6",
     "tags": ["勇敢", "领先"]},
    {"idiom": "画龙点睛", "pinyin": "huà lóng diǎn jīng",
     "meaning": "原形容梁代画家张僧繇作画的神妙。后多比喻写文章或讲话时，在关键处用几句话点明实质，使内容生动有力。",
     "story": "南朝梁代有位画家叫张僧繇，他画的龙特别逼真。传说有一次，他在金陵安乐寺的墙上画了四条龙，但都没有画眼睛。有人问他为什么，他说：\"如果画上眼睛，龙就会飞走。\"人们不信，非要他画上眼睛。张僧繇无奈，只好为两条龙画上了眼睛。刚画完，天空中就电闪雷鸣，这两条龙真的破壁飞走了。",
     "origin": "唐·张彦远《历代名画记·张僧繇》：\"武帝崇饰佛寺，多命僧繇画之……又金陵安乐寺四白龙不点眼睛，每云：'点睛即飞去。'人以为妄诞，固请点之。\"",
     "part_of_speech": "成语",
     "usage": "这篇文章的结尾部分真是画龙点睛，使整篇文章的主题更加鲜明了。",
     "synonyms": ["锦上添花", "点石成金"],
     "antonyms": ["画蛇添足", "弄巧成拙"],
     "difficulty": 3, "is_common": 1, "grade_level": "6-9",
     "tags": ["绘画", "关键"]},
    {"idiom": "对牛弹琴", "pinyin": "duì niú tán qín",
     "meaning": "比喻对不懂道理的人讲道理，白费口舌。也用来讥笑说话的人不看对象。",
     "story": "古时候，有个叫公明仪的音乐家，他弹琴的技艺非常高超。有一天，他看到一头牛在草地上吃草，就想给牛弹奏一曲。他弹了一首非常优美的曲子，但牛却毫无反应，继续低头吃草。",
     "origin": "汉·牟融《理惑论》：\"公明仪为牛弹清角之操，伏食如故。非牛不闻，不合其耳矣。\"",
     "part_of_speech": "成语",
     "usage": "跟他讲道理简直是对牛弹琴，他根本听不进去。",
     "synonyms": ["白费口舌", "徒劳无功"],
     "antonyms": ["有的放矢", "对症下药"],
     "difficulty": 2, "is_common": 1, "grade_level": "3-6",
     "tags": ["白费", "沟通"]},
    {"idiom": "井底之蛙", "pinyin": "jǐng dǐ zhī wā",
     "meaning": "井底的蛙只能看到井口那么大的一块天。比喻见识狭隘的人。",
     "story": "有一只青蛙住在井里。有一天，它对来自东海的大海龟说：\"你看我多快乐！在井里，我就是主人，想跳就跳，想休息就休息。\"大海龟听了，想进去看看，但井口太小，它进不去。",
     "origin": "《庄子·秋水》：\"井蛙不可以语于海者，拘于虚也。\"",
     "part_of_speech": "成语",
     "usage": "我们不能做井底之蛙，要多出去看看，开阔眼界。",
     "synonyms": ["坐井观天", "鼠目寸光"],
     "antonyms": ["见多识广", "博古通今"],
     "difficulty": 2, "is_common": 1, "grade_level": "3-6",
     "tags": ["见识", "狭隘"]},
    {"idiom": "守株待兔", "pinyin": "shǒu zhū dài tù",
     "meaning": "原比喻希图不经过努力而得到成功的侥幸心理。现也比喻死守狭隘经验，不知变通。",
     "story": "古时候，宋国有一个农夫。有一天，他看见一只兔子飞快地跑过来，一头撞在田边的树桩上，当场死了。农夫高兴极了，他捡起兔子回家，美美地吃了一顿。从此以后，他便放下手中的农活，天天守在树桩旁边。",
     "origin": "《韩非子·五蠹》：\"宋人有耕者。田中有株，兔走触株，折颈而死。因释其耒而守株，冀复得兔。\"",
     "part_of_speech": "成语",
     "usage": "我们不能守株待兔，要主动进取，才能取得成功。",
     "synonyms": ["坐享其成", "墨守成规"],
     "antonyms": ["随机应变", "积极进取"],
     "difficulty": 2, "is_common": 1, "grade_level": "3-6",
     "tags": ["侥幸", "变通"]},
    {"idiom": "刻舟求剑", "pinyin": "kè zhōu qiú jiàn",
     "meaning": "比喻拘泥成例，不知道跟着情势的变化而改变看法或办法。",
     "story": "有一个楚国人坐船渡江。船到江心时，他不小心把身上佩带的宝剑掉进了水里。他急忙在船舷上刻了一个记号，说：\"我的剑就是从这里掉下去的。\"船靠岸后，他就顺着船上刻的记号下水去找剑。",
     "origin": "《吕氏春秋·察今》：\"楚人有涉江者，其剑自舟中坠于水，遽契其舟曰：'是吾剑之所从坠。'舟止，从其所契者入水求之。\"",
     "part_of_speech": "成语",
     "usage": "我们要根据实际情况灵活处理问题，不能刻舟求剑。",
     "synonyms": ["墨守成规", "守旧不变"],
     "antonyms": ["随机应变", "与时俱进"],
     "difficulty": 2, "is_common": 1, "grade_level": "3-6",
     "tags": ["变通", "灵活"]},
    {"idiom": "掩耳盗铃", "pinyin": "yǎn ěr dào líng",
     "meaning": "偷铃铛怕别人听见而捂住自己的耳朵。比喻自己欺骗自己，明明掩盖不住的事情偏要想法子掩盖。",
     "story": "古时候，有一个人想偷别人家门口挂着的铃铛。他知道铃铛一碰就会响，被人发现。于是他想了一个办法：用手捂住自己的耳朵，这样自己就听不见铃铛的声音了。",
     "origin": "《吕氏春秋·自知》：\"百姓有得钟者，欲负而走，则钟大不可负。以椎毁之，钟况然有声。恐人闻之而夺己也，遽掩其耳。\"",
     "part_of_speech": "成语",
     "usage": "你这种做法简直是掩耳盗铃，以为别人不知道吗？",
     "synonyms": ["自欺欺人", "欲盖弥彰"],
     "antonyms": ["实事求是", "光明磊落"],
     "difficulty": 2, "is_common": 1, "grade_level": "3-6",
     "tags": ["自欺", "掩盖"]},
    {"idiom": "亡羊补牢", "pinyin": "wáng yáng bǔ láo",
     "meaning": "羊逃跑了再去修补羊圈，还不算晚。比喻出了问题以后想办法补救，可以防止继续受损失。",
     "story": "古时候，有一个人养了一群羊。有一天，他发现羊圈破了一个洞，一只羊丢了。邻居劝他赶紧把羊圈修好，但他不听。第二天，他又丢了一只羊。他这才后悔没有听邻居的劝告，赶紧把羊圈修好了。",
     "origin": "《战国策·楚策四》：\"见兔而顾犬，未为晚也；亡羊而补牢，未为迟也。\"",
     "part_of_speech": "成语",
     "usage": "虽然犯了错误，但亡羊补牢，还来得及补救。",
     "synonyms": ["知错能改", "防患未然"],
     "antonyms": ["执迷不悟", "知错不改"],
     "difficulty": 2, "is_common": 1, "grade_level": "3-6",
     "tags": ["补救", "改正"]},
    {"idiom": "拔苗助长", "pinyin": "bá miáo zhù zhǎng",
     "meaning": "把苗拔起来，帮助其生长。比喻违反事物的发展规律，急于求成，反而坏事。",
     "story": "古时候，宋国有一个农夫，他希望自己田里的禾苗长得快一些。于是他每天都到田里去看，但禾苗好像一点也没有长高。他很着急，就想出了一个办法：把禾苗一棵一棵地拔高。",
     "origin": "《孟子·公孙丑上》：\"宋人有悯其苗之不长而揠之者，芒芒然归，谓其人曰：'今日病矣！予助苗长矣！'其子趋而往视之，苗则槁矣。\"",
     "part_of_speech": "成语",
     "usage": "教育孩子要循序渐进，不能拔苗助长。",
     "synonyms": ["急于求成", "揠苗助长"],
     "antonyms": ["循序渐进", "顺其自然"],
     "difficulty": 2, "is_common": 1, "grade_level": "3-6",
     "tags": ["规律", "急躁"]},
    {"idiom": "卧薪尝胆", "pinyin": "wò xīn cháng dǎn",
     "meaning": "睡觉睡在柴草上，吃饭睡觉都尝一尝苦胆。形容人刻苦自励，发奋图强。",
     "story": "春秋时期，越国被吴国打败，越王勾践被迫到吴国做奴隶。他忍辱负重，终于得到机会回到越国。回国后，他立志报仇雪恨。为了时刻提醒自己不忘耻辱，他每天睡在柴草上，吃饭前都要尝一尝苦胆。",
     "origin": "《史记·越王勾践世家》：\"越王勾践反国，乃苦身焦思，置胆于坐，坐卧即仰胆，饮食亦尝胆也。\"",
     "part_of_speech": "成语",
     "usage": "他卧薪尝胆，终于实现了自己的梦想。",
     "synonyms": ["发奋图强", "励精图治"],
     "antonyms": ["安于享乐", "不思进取"],
     "difficulty": 3, "is_common": 1, "grade_level": "6-9",
     "tags": ["励志", "奋斗"]}
]


XIEHOUYU = [
    {"front_part": "十五个吊桶打水", "back_part": "七上八下",
     "pinyin": "shi wu ge diao tong da shui - qi shang ba xia",
     "meaning": "形容心情非常紧张、忐忑不安。",
     "usage": "明天就要考试了，他心里像十五个吊桶打水——七上八下。",
     "difficulty": 1, "is_common": 1, "grade_level": "1-3",
     "tags": ["心情", "紧张"]},
    {"front_part": "小葱拌豆腐", "back_part": "一清二白",
     "pinyin": "xiao cong ban dou fu - yi qing er bai",
     "meaning": "比喻事情非常清楚，没有任何隐瞒。",
     "usage": "这件事的来龙去脉我已经调查清楚了，那真是小葱拌豆腐——一清二白。",
     "difficulty": 1, "is_common": 1, "grade_level": "1-3",
     "tags": ["清楚", "明白"]},
    {"front_part": "黄鼠狼给鸡拜年", "back_part": "没安好心",
     "pinyin": "huang shu lang gei ji bai nian - mei an hao xin",
     "meaning": "比喻表面上假装友好，实际上心怀恶意。",
     "usage": "他突然对我这么热情，肯定是黄鼠狼给鸡拜年——没安好心。",
     "difficulty": 1, "is_common": 1, "grade_level": "1-3",
     "tags": ["虚伪", "恶意"]},
    {"front_part": "外甥打灯笼", "back_part": "照旧",
     "pinyin": "wai sheng da deng long - zhao jiu",
     "meaning": "比喻事情和原来一样，没有变化。",
     "usage": "虽然换了领导，但工作方式还是外甥打灯笼——照旧。",
     "difficulty": 1, "is_common": 1, "grade_level": "1-3",
     "tags": ["不变", "照旧"]},
    {"front_part": "竹篮打水", "back_part": "一场空",
     "pinyin": "zhu lan da shui - yi chang kong",
     "meaning": "比喻白费力气，没有任何收获。",
     "usage": "他忙活了半天，结果竹篮打水——一场空。",
     "difficulty": 1, "is_common": 1, "grade_level": "1-3",
     "tags": ["白费", "徒劳"]},
    {"front_part": "哑巴吃黄连", "back_part": "有苦说不出",
     "pinyin": "ya ba chi huang lian - you ku shuo bu chu",
     "meaning": "比喻心里有苦却说不出来。",
     "usage": "他受了委屈，却没法解释，真是哑巴吃黄连——有苦说不出。",
     "difficulty": 2, "is_common": 1, "grade_level": "3-6",
     "tags": ["委屈", "无奈"]},
    {"front_part": "热锅上的蚂蚁", "back_part": "团团转",
     "pinyin": "re guo shang de ma yi - tuan tuan zhuan",
     "meaning": "形容人非常着急、焦虑不安。",
     "usage": "考试快开始了，他还没找到准考证，急得像热锅上的蚂蚁——团团转。",
     "difficulty": 1, "is_common": 1, "grade_level": "1-3",
     "tags": ["着急", "焦虑"]}
]


LITERATURE_SEGMENTS = [
    {"title": "红楼梦·葬花吟", "author": "曹雪芹", "work": "红楼梦",
     "content": "花谢花飞花满天，红消香断有谁怜？\n游丝软系飘春榭，落絮轻沾扑绣帘。\n闺中女儿惜春暮，愁绪满怀无释处。\n手把花锄出绣帘，忍踏落花来复去。",
     "summary": "这段文字描写了林黛玉葬花的情景，表达了她对生命短暂和命运无常的感慨。",
     "analysis": "《葬花吟》是林黛玉在葬花时所作的诗，通过对落花的描写，表达了她内心的孤独、忧愁和对未来的迷茫。",
     "literary_device": "拟人、比喻、对比",
     "theme": "生命、命运",
     "origin_country": "中国", "time_period": "清代",
     "grade_level": "9", "difficulty": 4, "is_classic": 1,
     "tags": ["红楼梦", "林黛玉", "古典文学"]},
    {"title": "呐喊·自序", "author": "鲁迅", "work": "呐喊",
     "content": "我在年青时候也曾经做过许多梦，后来大半忘却了，但自己也并不以为可惜。所谓回忆者，虽说可以使人欢欣，有时也不免使人寂寞，使精神的丝缕还牵着已逝的寂寞的时光。",
     "summary": "这段文字讲述了鲁迅创作《呐喊》的缘由，表达了他对社会现实的关注和对国民性的思考。",
     "analysis": "作者通过回忆自己年轻时的梦想，引出创作《呐喊》的初衷。文字朴实但蕴含深刻的思想，体现了鲁迅作为思想家的敏锐和深刻。",
     "literary_device": "象征、抒情",
     "theme": "觉醒、批判",
     "origin_country": "中国", "time_period": "现代",
     "grade_level": "9", "difficulty": 4, "is_classic": 1,
     "tags": ["鲁迅", "呐喊", "现代文学"]},
    {"title": "荷塘月色", "author": "朱自清", "work": "朱自清散文",
     "content": "曲曲折折的荷塘上面，弥望的是田田的叶子。叶子出水很高，像亭亭的舞女的裙。层层的叶子中间，零星地点缀着些白花，有袅娜地开着的，有羞涩地打着朵儿的。",
     "summary": "这段文字描写了荷塘月色的美丽景色，通过细腻的描写展现了作者内心的宁静与美好。",
     "analysis": "作者运用比喻、拟人等修辞手法，从不同角度描绘了荷塘的美景。语言优美，意境深远，是现代散文的经典之作。",
     "literary_device": "比喻、拟人、通感",
     "theme": "自然、宁静",
     "origin_country": "中国", "time_period": "现代",
     "grade_level": "8", "difficulty": 3, "is_classic": 1,
     "tags": ["朱自清", "散文", "自然"]},
    {"title": "骆驼祥子", "author": "老舍", "work": "骆驼祥子",
     "content": "祥子的手哆嗦得更厉害了，揣起保单，拉起车，几乎要哭出来。拉到个僻静地方，细细端详自己的车，在漆板上试着照照自己的脸！越看越可爱。",
     "summary": "这段文字描写了祥子买到第一辆车时的激动心情，展现了他对生活的希望和追求。",
     "analysis": "作者通过细节描写，刻画了祥子买到车后的激动和喜悦。\"手哆嗦\"\"几乎要哭出来\"等细节，生动地表现了祥子对这辆车的珍视和对未来的憧憬。",
     "literary_device": "细节描写、心理描写",
     "theme": "希望、奋斗",
     "origin_country": "中国", "time_period": "现代",
     "grade_level": "9", "difficulty": 4, "is_classic": 1,
     "tags": ["老舍", "骆驼祥子", "社会"]},
    {"title": "雷雨", "author": "曹禺", "work": "雷雨",
     "content": "周朴园：（忽然严厉地）你来干什么？\n鲁侍萍：不是我要来的。\n周朴园：谁指使你来的？\n鲁侍萍：（悲愤）命！不公平的命指使我来的！",
     "summary": "这段对话展现了周朴园和鲁侍萍之间复杂的情感纠葛和阶级对立。",
     "analysis": "通过简短的对话，作者揭示了人物之间复杂的关系和矛盾冲突。周朴园的冷酷和鲁侍萍的悲愤形成鲜明对比。",
     "literary_device": "对话、对比",
     "theme": "命运、阶级",
     "origin_country": "中国", "time_period": "现代",
     "grade_level": "9", "difficulty": 4, "is_classic": 1,
     "tags": ["曹禺", "雷雨", "戏剧"]}
]


READING_COMPREHENSION = [
    {"title": "春的消息",
     "article": "春天来了，小草从土里探出头来，好奇地打量着这个世界。柳树抽出了嫩绿的枝条，在微风中轻轻摇曳。花儿们也不甘示弱，红的、黄的、粉的，争奇斗艳。小燕子从南方飞回来了，它们在天空中快乐地飞翔，叽叽喳喳地叫着，好像在说：\"春天来了！春天来了！\"",
     "questions": ["文章中提到了哪些春天的景物？", "小燕子是从哪里飞回来的？", "用自己的话说说春天的特点。"],
     "answers": ["小草、柳树、花儿、小燕子", "南方", "春天万物复苏，生机勃勃，景色美丽。"],
     "analysis": ["仔细阅读文章，可以找到\"小草\"\"柳树\"\"花儿\"\"小燕子\"这些春天的景物。",
                  "文章中明确写了\"小燕子从南方飞回来了\"。",
                  "通过文章对各种景物的描写，可以总结出春天万物复苏、生机勃勃的特点。"],
     "genre": "记叙文", "subject": "chinese", "grade_level": "1-3",
     "difficulty": 1, "time_limit": 10, "score": 15,
     "tags": ["春天", "自然"]},
    {"title": "母爱",
     "article": "记得那年冬天，我生病了，妈妈背着我去医院。雪下得很大，妈妈的衣服都湿透了，但她还是紧紧地抱着我。到了医院，妈妈又忙着挂号、拿药，直到我打完针，她才松了一口气。",
     "questions": ["文章讲述了一件什么事？", "从哪些地方可以看出妈妈很爱\"我\"？", "读了这篇文章，你有什么感受？"],
     "answers": ["冬天\"我\"生病，妈妈背着\"我\"去医院看病。",
                 "妈妈背着\"我\"在大雪中去医院，衣服湿透了还紧紧抱着\"我\"；到医院后忙着挂号、拿药；一直等到\"我\"打完针才松口气。",
                 "感受到母爱的伟大和无私，我们应该珍惜和感恩。"],
     "analysis": ["概括文章的主要内容，抓住时间、人物、事件等要素。",
                  "从妈妈的动作和表现中寻找体现母爱的细节。",
                  "结合自己的生活体验，表达对母爱的理解和感受。"],
     "genre": "记叙文", "subject": "chinese", "grade_level": "3-6",
     "difficulty": 2, "time_limit": 15, "score": 20,
     "tags": ["母爱", "情感"]},
    {"title": "读书的好处",
     "article": "读书可以增长知识。通过读书，我们可以了解到很多我们不知道的事情，比如历史、科学、文化等。读书还可以提高我们的写作能力。多读书，我们的词汇量会增加，表达能力也会变得更好。",
     "questions": ["文章中提到了读书的哪些好处？", "为什么说读书可以提高写作能力？", "你认为读书还有哪些好处？"],
     "answers": ["增长知识、提高写作能力、让我们变得更聪明。",
                 "因为多读书可以增加词汇量，提高表达能力。",
                 "读书还可以开阔视野、培养兴趣、放松心情等。"],
     "analysis": ["从文章中找出\"读书可以增长知识\"\"读书还可以提高我们的写作能力\"\"读书可以让我们变得更聪明\"这些句子。",
                  "文章中说\"多读书，我们的词汇量会增加，表达能力也会变得更好\"，这就是读书能提高写作能力的原因。",
                  "结合自己的读书体验，说出读书的其他好处。"],
     "genre": "议论文", "subject": "chinese", "grade_level": "3-6",
     "difficulty": 2, "time_limit": 15, "score": 20,
     "tags": ["读书", "议论文"]}
]


FAMOUS_QUOTES = [
    {"content": "学而不思则罔，思而不学则殆。", "author": "孔子", "source": "论语·为政",
     "category": "学习", "language": "chinese", "grade_level": "6-9",
     "difficulty": 3, "is_classic": 1, "tags": ["学习", "思考", "论语"]},
    {"content": "三人行，必有我师焉。择其善者而从之，其不善者而改之。", "author": "孔子", "source": "论语·述而",
     "category": "学习", "language": "chinese", "grade_level": "6-9",
     "difficulty": 3, "is_classic": 1, "tags": ["学习", "谦虚", "论语"]},
    {"content": "知之者不如好之者，好之者不如乐之者。", "author": "孔子", "source": "论语·雍也",
     "category": "学习", "language": "chinese", "grade_level": "6-9",
     "difficulty": 3, "is_classic": 1, "tags": ["学习", "兴趣", "论语"]},
    {"content": "业精于勤，荒于嬉；行成于思，毁于随。", "author": "韩愈", "source": "劝学诗",
     "category": "学习", "language": "chinese", "grade_level": "6-9",
     "difficulty": 3, "is_classic": 1, "tags": ["学习", "勤奋", "韩愈"]},
    {"content": "书籍是人类进步的阶梯。", "author": "高尔基", "source": "高尔基文集",
     "category": "读书", "language": "chinese", "grade_level": "3-6",
     "difficulty": 2, "is_classic": 1, "tags": ["读书", "高尔基", "励志"]},
    {"content": "人生自古谁无死，留取丹心照汗青。", "author": "文天祥", "source": "过零丁洋",
     "category": "爱国", "language": "chinese", "grade_level": "6-9",
     "difficulty": 3, "is_classic": 1, "tags": ["爱国", "文天祥", "气节"]},
    {"content": "先天下之忧而忧，后天下之乐而乐。", "author": "范仲淹", "source": "岳阳楼记",
     "category": "爱国", "language": "chinese", "grade_level": "6-9",
     "difficulty": 3, "is_classic": 1, "tags": ["爱国", "范仲淹", "忧乐观"]},
    {"content": "路漫漫其修远兮，吾将上下而求索。", "author": "屈原", "source": "离骚",
     "category": "励志", "language": "chinese", "grade_level": "6-9",
     "difficulty": 4, "is_classic": 1, "tags": ["励志", "屈原", "求索"]},
    {"content": "宝剑锋从磨砺出，梅花香自苦寒来。", "author": "佚名", "source": "警世贤文",
     "category": "励志", "language": "chinese", "grade_level": "3-6",
     "difficulty": 2, "is_classic": 1, "tags": ["励志", "磨砺", "奋斗"]},
    {"content": "少壮不努力，老大徒伤悲。", "author": "佚名", "source": "长歌行",
     "category": "励志", "language": "chinese", "grade_level": "1-3",
     "difficulty": 1, "is_classic": 1, "tags": ["励志", "惜时", "努力"]},
    {"content": "Where there is a will, there is a way.", "author": "English Proverb", "source": "English Proverbs",
     "category": "励志", "language": "english", "grade_level": "3-6",
     "difficulty": 2, "is_classic": 1, "tags": ["励志", "英语谚语"]},
    {"content": "Knowledge is power.", "author": "Francis Bacon", "source": "Essays",
     "category": "知识", "language": "english", "grade_level": "6-9",
     "difficulty": 2, "is_classic": 1, "tags": ["知识", "培根", "英语"]}
]
