# js-encrypt-monitor 服务配置
# 生成时间: 2025-11-09 21:34:34
SERVICE_TYPE="node"
SERVICE_FILE="/Users/wuchenghao/Library/CloudStorage/OneDrive-个人/文档/MTSCOS_AI_Project/JavaScript/js-encrypt-monitor.js"
SERVICE_ARGS=""
